<?php

namespace DoctrineORMModule\Proxy\__CG__\LundProducts\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductLines extends \LundProducts\Entity\ProductLines implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'name', 'bpcsCode', 'shortCode', 'displayName', 'overview', 'websiteOverview', 'teaser', 'position', 'brandPosition', 'totalCount', 'saleable', 'installationVideo', 'metaTitle', 'metaKeywords', 'metaDescr', 'totalRating', 'productLineId', 'productCategory', 'brand', 'origBrand', 'productLineAsset', 'comparisonChart');
        }

        return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'name', 'bpcsCode', 'shortCode', 'displayName', 'overview', 'websiteOverview', 'teaser', 'position', 'brandPosition', 'totalCount', 'saleable', 'installationVideo', 'metaTitle', 'metaKeywords', 'metaDescr', 'totalRating', 'productLineId', 'productCategory', 'brand', 'origBrand', 'productLineAsset', 'comparisonChart');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductLines $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt($modifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', array($modifiedAt));

        return parent::setModifiedAt($modifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', array());

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisabled($disabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisabled', array($disabled));

        return parent::setDisabled($disabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabled', array());

        return parent::getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBpcsCode($bpcsCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBpcsCode', array($bpcsCode));

        return parent::setBpcsCode($bpcsCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBpcsCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBpcsCode', array());

        return parent::getBpcsCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortCode($shortCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortCode', array($shortCode));

        return parent::setShortCode($shortCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortCode', array());

        return parent::getShortCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayname($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayname', array($displayName));

        return parent::setDisplayname($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', array());

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOverview($overview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverview', array($overview));

        return parent::setOverview($overview);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverview', array());

        return parent::getOverview();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsiteOverview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsiteOverview', array());

        return parent::getWebsiteOverview();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsiteOverview($websiteOverview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsiteOverview', array($websiteOverview));

        return parent::setWebsiteOverview($websiteOverview);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeaser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeaser', array());

        return parent::getTeaser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeaser($teaser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeaser', array($teaser));

        return parent::setTeaser($teaser);
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCount($totalCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCount', array($totalCount));

        return parent::setTotalCount($totalCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCount', array());

        return parent::getTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrandPosition($brandPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrandPosition', array($brandPosition));

        return parent::setBrandPosition($brandPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandPosition', array());

        return parent::getBrandPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaleable($saleable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaleable', array($saleable));

        return parent::setSaleable($saleable);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaleable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaleable', array());

        return parent::getSaleable();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstallationVideo($installationVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstallationVideo', array($installationVideo));

        return parent::setInstallationVideo($installationVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstallationVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstallationVideo', array());

        return parent::getInstallationVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaTitle($metaTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaTitle', array($metaTitle));

        return parent::setMetaTitle($metaTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaTitle', array());

        return parent::getMetaTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaKeywords($metaKeywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaKeywords', array($metaKeywords));

        return parent::setMetaKeywords($metaKeywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaKeywords', array());

        return parent::getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDescr($metaDescr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDescr', array($metaDescr));

        return parent::setMetaDescr($metaDescr);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescr', array());

        return parent::getMetaDescr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalRating($totalRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalRating', array($totalRating));

        return parent::setTotalRating($totalRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalRating', array());

        return parent::getTotalRating();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductLineId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProductLineId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductLineId', array());

        return parent::getProductLineId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCategory(\LundProducts\Entity\ProductCategories $productCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCategory', array($productCategory));

        return parent::setProductCategory($productCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCategory', array());

        return parent::getProductCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(\LundProducts\Entity\Brands $brand = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', array($brand));

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', array());

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigBrand(\LundProducts\Entity\Brands $origBrand = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigBrand', array($origBrand));

        return parent::setOrigBrand($origBrand);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigBrand', array());

        return parent::getOrigBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setComparisonChart(\LundSite\Entity\ComparisonChart $comparisonChart = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComparisonChart', array($comparisonChart));

        return parent::setComparisonChart($comparisonChart);
    }

    /**
     * {@inheritDoc}
     */
    public function getComparisonChart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComparisonChart', array());

        return parent::getComparisonChart();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductLineAsset(\LundProducts\Entity\ProductLineAsset $productLineAsset = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductLineAsset', array($productLineAsset));

        return parent::setProductLineAsset($productLineAsset);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductLineAsset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductLineAsset', array());

        return parent::getProductLineAsset();
    }

}
