<?php

namespace DoctrineORMModule\Proxy\__CG__\LundProducts\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promo extends \LundProducts\Entity\Promo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'customerNumber', 'startDate', 'endDate', 'promoDesc', 'promoCode', 'promoNumber', 'promoLine', 'price', 'percent', 'promoPrice', 'promoOff', 'customerPromo', 'itemClassPromo', 'itemPromo', 'description', 'promoId', 'parts', 'productLine');
        }

        return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'customerNumber', 'startDate', 'endDate', 'promoDesc', 'promoCode', 'promoNumber', 'promoLine', 'price', 'percent', 'promoPrice', 'promoOff', 'customerPromo', 'itemClassPromo', 'itemPromo', 'description', 'promoId', 'parts', 'productLine');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Promo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt($modifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', array($modifiedAt));

        return parent::setModifiedAt($modifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', array());

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisabled($disabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisabled', array($disabled));

        return parent::setDisabled($disabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabled', array());

        return parent::getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerNumber($customerNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerNumber', array($customerNumber));

        return parent::setCustomerNumber($customerNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerNumber', array());

        return parent::getCustomerNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate($startDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', array($startDate));

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', array());

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate($endDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', array($endDate));

        return parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', array());

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoDesc($promoDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoDesc', array($promoDesc));

        return parent::setPromoDesc($promoDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoDesc', array());

        return parent::getPromoDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoCode($promoCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoCode', array($promoCode));

        return parent::setPromoCode($promoCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoCode', array());

        return parent::getPromoCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoNumber($promoNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoNumber', array($promoNumber));

        return parent::setPromoNumber($promoNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoNumber', array());

        return parent::getPromoNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoLine($promoLine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoLine', array($promoLine));

        return parent::setPromoLine($promoLine);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoLine', array());

        return parent::getPromoLine();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercent($percent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercent', array($percent));

        return parent::setPercent($percent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercent', array());

        return parent::getPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoPrice($promoPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoPrice', array($promoPrice));

        return parent::setPromoPrice($promoPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoPrice', array());

        return parent::getPromoPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoOff($promoOff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoOff', array($promoOff));

        return parent::setPromoOff($promoOff);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoOff()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoOff', array());

        return parent::getPromoOff();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerPromo($customerPromo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerPromo', array($customerPromo));

        return parent::setCustomerPromo($customerPromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerPromo', array());

        return parent::getCustomerPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemClassPromo($itemClassPromo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemClassPromo', array($itemClassPromo));

        return parent::setItemClassPromo($itemClassPromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemClassPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemClassPromo', array());

        return parent::getItemClassPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemPromo($itemPromo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemPromo', array($itemPromo));

        return parent::setItemPromo($itemPromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemPromo', array());

        return parent::getItemPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setParts(\LundProducts\Entity\Parts $parts = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParts', array($parts));

        return parent::setParts($parts);
    }

    /**
     * {@inheritDoc}
     */
    public function getParts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParts', array());

        return parent::getParts();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductLine(\LundProducts\Entity\ProductLines $productLine = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductLine', array($productLine));

        return parent::setProductLine($productLine);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductLine', array());

        return parent::getProductLine();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPromoId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoId', array());

        return parent::getPromoId();
    }

}
