<?php

namespace DoctrineORMModule\Proxy\__CG__\LundProducts\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ChangesetDetailsVehicles extends \LundProducts\Entity\ChangesetDetailsVehicles implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehMakeLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehModelLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehSubmodelLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehYearLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehClassLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'changesetDetailVehicleId', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehCollection', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehMake', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehModel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehSubmodel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehYear', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehClass', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'changesetDetails');
        }

        return array('__isInitialized__', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehMakeLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehModelLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehSubmodelLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehYearLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehClassLabel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'changesetDetailVehicleId', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehCollection', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehMake', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehModel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehSubmodel', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehYear', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'vehClass', '' . "\0" . 'LundProducts\\Entity\\ChangesetDetailsVehicles' . "\0" . 'changesetDetails');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ChangesetDetailsVehicles $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setVehMakeLabel($vehMakeLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehMakeLabel', array($vehMakeLabel));

        return parent::setVehMakeLabel($vehMakeLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehMakeLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehMakeLabel', array());

        return parent::getVehMakeLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehModelLabel($vehModelLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehModelLabel', array($vehModelLabel));

        return parent::setVehModelLabel($vehModelLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehModelLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehModelLabel', array());

        return parent::getVehModelLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehSubmodelLabel($vehSubmodelLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehSubmodelLabel', array($vehSubmodelLabel));

        return parent::setVehSubmodelLabel($vehSubmodelLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehSubmodelLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehSubmodelLabel', array());

        return parent::getVehSubmodelLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehYearLabel($vehYearLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehYearLabel', array($vehYearLabel));

        return parent::setVehYearLabel($vehYearLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehYearLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehYearLabel', array());

        return parent::getVehYearLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehClassLabel($vehClassLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehClassLabel', array($vehClassLabel));

        return parent::setVehClassLabel($vehClassLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehClassLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehClassLabel', array());

        return parent::getVehClassLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function getChangesetDetailVehicleId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getChangesetDetailVehicleId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChangesetDetailVehicleId', array());

        return parent::getChangesetDetailVehicleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehCollection(\LundProducts\Entity\VehCollection $vehCollection = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehCollection', array($vehCollection));

        return parent::setVehCollection($vehCollection);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehCollection', array());

        return parent::getVehCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehMake(\LundProducts\Entity\VehMake $vehMake = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehMake', array($vehMake));

        return parent::setVehMake($vehMake);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehMake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehMake', array());

        return parent::getVehMake();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehModel(\LundProducts\Entity\VehModel $vehModel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehModel', array($vehModel));

        return parent::setVehModel($vehModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehModel', array());

        return parent::getVehModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehSubmodel(\LundProducts\Entity\VehSubmodel $vehSubmodel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehSubmodel', array($vehSubmodel));

        return parent::setVehSubmodel($vehSubmodel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehSubmodel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehSubmodel', array());

        return parent::getVehSubmodel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehYear(\LundProducts\Entity\VehYear $vehYear = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehYear', array($vehYear));

        return parent::setVehYear($vehYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehYear', array());

        return parent::getVehYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehClass(\LundProducts\Entity\VehClass $vehClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehClass', array($vehClass));

        return parent::setVehClass($vehClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehClass', array());

        return parent::getVehClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setChangesetDetails(\LundProducts\Entity\ChangesetDetails $changesetDetails = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChangesetDetails', array($changesetDetails));

        return parent::setChangesetDetails($changesetDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getChangesetDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChangesetDetails', array());

        return parent::getChangesetDetails();
    }

}
