<?php

namespace DoctrineORMModule\Proxy\__CG__\LundProducts\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VehCollection extends \LundProducts\Entity\VehCollection implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'vehCollectionId', 'vehCollections', 'vehMake', 'vehModel', 'vehSubmodel', 'vehYear', 'part', 'makeId', 'modelId', 'submodelId', 'bodyTypeId', 'bodyType', 'bodyNumDoorsId', 'bedTypeId', 'bedType', 'modelType', 'baseVehId', 'fitCode1', 'fitCode1Desc', 'fitCode2', 'fitCode2Desc', 'fitCode3', 'fitCode3Desc', 'fitCode4', 'fitCode4Desc', 'fitCode5', 'fitCode5Desc', 'jeepClearance');
        }

        return array('__isInitialized__', 'vehCollectionId', 'vehCollections', 'vehMake', 'vehModel', 'vehSubmodel', 'vehYear', 'part', 'makeId', 'modelId', 'submodelId', 'bodyTypeId', 'bodyType', 'bodyNumDoorsId', 'bedTypeId', 'bedType', 'modelType', 'baseVehId', 'fitCode1', 'fitCode1Desc', 'fitCode2', 'fitCode2Desc', 'fitCode3', 'fitCode3Desc', 'fitCode4', 'fitCode4Desc', 'fitCode5', 'fitCode5Desc', 'jeepClearance');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VehCollection $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getVehCollectionId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getVehCollectionId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehCollectionId', array());

        return parent::getVehCollectionId();
    }

    /**
     * {@inheritDoc}
     */
    public function addVehCollection(\LundProducts\Entity\PartVehCollection $vehCollections)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVehCollection', array($vehCollections));

        return parent::addVehCollection($vehCollections);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVehCollection(\LundProducts\Entity\PartVehCollection $vehCollections)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVehCollection', array($vehCollections));

        return parent::removeVehCollection($vehCollections);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehCollections()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehCollections', array());

        return parent::getVehCollections();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehMake(\LundProducts\Entity\VehMake $vehMake = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehMake', array($vehMake));

        return parent::setVehMake($vehMake);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehMake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehMake', array());

        return parent::getVehMake();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehModel(\LundProducts\Entity\VehModel $vehModel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehModel', array($vehModel));

        return parent::setVehModel($vehModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehModel', array());

        return parent::getVehModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehSubmodel(\LundProducts\Entity\VehSubmodel $vehSubmodel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehSubmodel', array($vehSubmodel));

        return parent::setVehSubmodel($vehSubmodel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehSubmodel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehSubmodel', array());

        return parent::getVehSubmodel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehYear(\LundProducts\Entity\VehYear $vehYear = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehYear', array($vehYear));

        return parent::setVehYear($vehYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehYear', array());

        return parent::getVehYear();
    }

    /**
     * {@inheritDoc}
     */
    public function addPart(\LundProducts\Entity\Parts $part)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPart', array($part));

        return parent::addPart($part);
    }

    /**
     * {@inheritDoc}
     */
    public function removePart(\LundProducts\Entity\Parts $part)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePart', array($part));

        return parent::removePart($part);
    }

    /**
     * {@inheritDoc}
     */
    public function getPart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPart', array());

        return parent::getPart();
    }

    /**
     * {@inheritDoc}
     */
    public function setMakeId($makeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMakeId', array($makeId));

        return parent::setMakeId($makeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMakeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMakeId', array());

        return parent::getMakeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelId($modelId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelId', array($modelId));

        return parent::setModelId($modelId);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelId', array());

        return parent::getModelId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmodelId($submodelId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmodelId', array($submodelId));

        return parent::setSubmodelId($submodelId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmodelId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmodelId', array());

        return parent::getSubmodelId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBodyTypeId($bodyTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBodyTypeId', array($bodyTypeId));

        return parent::setBodyTypeId($bodyTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBodyTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBodyTypeId', array());

        return parent::getBodyTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBodyType($bodyType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBodyType', array($bodyType));

        return parent::setBodyType($bodyType);
    }

    /**
     * {@inheritDoc}
     */
    public function getBodyType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBodyType', array());

        return parent::getBodyType();
    }

    /**
     * {@inheritDoc}
     */
    public function setBodyNumDoorsId($bodyNumDoorsId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBodyNumDoorsId', array($bodyNumDoorsId));

        return parent::setBodyNumDoorsId($bodyNumDoorsId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBodyNumDoorsId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBodyNumDoorsId', array());

        return parent::getBodyNumDoorsId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBedTypeId($bedTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBedTypeId', array($bedTypeId));

        return parent::setBedTypeId($bedTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBedTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBedTypeId', array());

        return parent::getBedTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBedType($bedType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBedType', array($bedType));

        return parent::setBedType($bedType);
    }

    /**
     * {@inheritDoc}
     */
    public function getBedType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBedType', array());

        return parent::getBedType();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelType($modelType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelType', array($modelType));

        return parent::setModelType($modelType);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelType', array());

        return parent::getModelType();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseVehId($baseVehId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseVehId', array($baseVehId));

        return parent::setBaseVehId($baseVehId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseVehId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseVehId', array());

        return parent::getBaseVehId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode1($fitCode1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode1', array($fitCode1));

        return parent::setFitCode1($fitCode1);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode1', array());

        return parent::getFitCode1();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode1Desc($fitCode1Desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode1Desc', array($fitCode1Desc));

        return parent::setFitCode1Desc($fitCode1Desc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode1Desc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode1Desc', array());

        return parent::getFitCode1Desc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode2($fitCode2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode2', array($fitCode2));

        return parent::setFitCode2($fitCode2);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode2', array());

        return parent::getFitCode2();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode2Desc($fitCode2Desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode2Desc', array($fitCode2Desc));

        return parent::setFitCode2Desc($fitCode2Desc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode2Desc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode2Desc', array());

        return parent::getFitCode2Desc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode3($fitCode3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode3', array($fitCode3));

        return parent::setFitCode3($fitCode3);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode3', array());

        return parent::getFitCode3();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode3Desc($fitCode3Desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode3Desc', array($fitCode3Desc));

        return parent::setFitCode3Desc($fitCode3Desc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode3Desc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode3Desc', array());

        return parent::getFitCode3Desc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode4($fitCode4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode4', array($fitCode4));

        return parent::setFitCode4($fitCode4);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode4', array());

        return parent::getFitCode4();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode4Desc($fitCode4Desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode4Desc', array($fitCode4Desc));

        return parent::setFitCode4Desc($fitCode4Desc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode4Desc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode4Desc', array());

        return parent::getFitCode4Desc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode5($fitCode5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode5', array($fitCode5));

        return parent::setFitCode5($fitCode5);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode5', array());

        return parent::getFitCode5();
    }

    /**
     * {@inheritDoc}
     */
    public function setFitCode5Desc($fitCode5Desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFitCode5Desc', array($fitCode5Desc));

        return parent::setFitCode5Desc($fitCode5Desc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFitCode5Desc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFitCode5Desc', array());

        return parent::getFitCode5Desc();
    }

    /**
     * {@inheritDoc}
     */
    public function setJeepClearance($jeepClearance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJeepClearance', array($jeepClearance));

        return parent::setJeepClearance($jeepClearance);
    }

    /**
     * {@inheritDoc}
     */
    public function getJeepClearance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJeepClearance', array());

        return parent::getJeepClearance();
    }

}
