<?php

namespace DoctrineORMModule\Proxy\__CG__\RocketEcom\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EcomCustomer extends \RocketEcom\Entity\EcomCustomer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'firstName', 'middleName', 'lastName', 'email', 'password', 'companyName', 'phoneNumber', 'faxNumber', 'billingStreetAddress', 'billingExtStreetAddress', 'billingCity', 'billingState', 'billingPostCode', 'billingCountry', 'shippingStreetAddress', 'shippingExtStreetAddress', 'shippingCity', 'shippingState', 'shippingPostCode', 'shippingCountry', 'newsletters', 'sameAsBilling', 'guest', 'ecomCustomerId', 'algorithm', 'salt', 'hashPasswordRequired');
        }

        return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'firstName', 'middleName', 'lastName', 'email', 'password', 'companyName', 'phoneNumber', 'faxNumber', 'billingStreetAddress', 'billingExtStreetAddress', 'billingCity', 'billingState', 'billingPostCode', 'billingCountry', 'shippingStreetAddress', 'shippingExtStreetAddress', 'shippingCity', 'shippingState', 'shippingPostCode', 'shippingCountry', 'newsletters', 'sameAsBilling', 'guest', 'ecomCustomerId', 'algorithm', 'salt', 'hashPasswordRequired');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EcomCustomer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt($modifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', array($modifiedAt));

        return parent::setModifiedAt($modifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', array());

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisabled($disabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisabled', array($disabled));

        return parent::setDisabled($disabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabled', array());

        return parent::getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiddleName($middleName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiddleName', array($middleName));

        return parent::setMiddleName($middleName);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiddleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiddleName', array());

        return parent::getMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName($companyName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', array($companyName));

        return parent::setCompanyName($companyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', array());

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', array($phoneNumber));

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', array());

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setFaxNumber($faxNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFaxNumber', array($faxNumber));

        return parent::setFaxNumber($faxNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaxNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaxNumber', array());

        return parent::getFaxNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingStreetAddress($billingStreetAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingStreetAddress', array($billingStreetAddress));

        return parent::setBillingStreetAddress($billingStreetAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingStreetAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingStreetAddress', array());

        return parent::getBillingStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingExtStreetAddress($billingExtStreetAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingExtStreetAddress', array($billingExtStreetAddress));

        return parent::setBillingExtStreetAddress($billingExtStreetAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingExtStreetAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingExtStreetAddress', array());

        return parent::getBillingExtStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingCity($billingCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingCity', array($billingCity));

        return parent::setBillingCity($billingCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingCity', array());

        return parent::getBillingCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingState(\RocketBase\Entity\State $billingState = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingState', array($billingState));

        return parent::setBillingState($billingState);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingState', array());

        return parent::getBillingState();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingPostCode($billingPostCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingPostCode', array($billingPostCode));

        return parent::setBillingPostCode($billingPostCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingPostCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingPostCode', array());

        return parent::getBillingPostCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingCountry(\RocketBase\Entity\Country $billingCountry = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingCountry', array($billingCountry));

        return parent::setBillingCountry($billingCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingCountry', array());

        return parent::getBillingCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingStreetAddress($shippingStreetAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingStreetAddress', array($shippingStreetAddress));

        return parent::setShippingStreetAddress($shippingStreetAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingStreetAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingStreetAddress', array());

        return parent::getShippingStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingExtStreetAddress($shippingExtStreetAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingExtStreetAddress', array($shippingExtStreetAddress));

        return parent::setShippingExtStreetAddress($shippingExtStreetAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingExtStreetAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingExtStreetAddress', array());

        return parent::getShippingExtStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCity($shippingCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCity', array($shippingCity));

        return parent::setShippingCity($shippingCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCity', array());

        return parent::getShippingCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingState(\RocketBase\Entity\State $shippingState = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingState', array($shippingState));

        return parent::setShippingState($shippingState);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingState', array());

        return parent::getShippingState();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingPostCode($shippingPostCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingPostCode', array($shippingPostCode));

        return parent::setShippingPostCode($shippingPostCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingPostCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingPostCode', array());

        return parent::getShippingPostCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCountry(\RocketBase\Entity\Country $shippingCountry = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCountry', array($shippingCountry));

        return parent::setShippingCountry($shippingCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCountry', array());

        return parent::getShippingCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsletters($newsletters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsletters', array($newsletters));

        return parent::setNewsletters($newsletters);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsletters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsletters', array());

        return parent::getNewsletters();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuest($guest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuest', array($guest));

        return parent::setGuest($guest);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuest', array());

        return parent::getGuest();
    }

    /**
     * {@inheritDoc}
     */
    public function setSameAsBilling($sameAsBilling)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSameAsBilling', array($sameAsBilling));

        return parent::setSameAsBilling($sameAsBilling);
    }

    /**
     * {@inheritDoc}
     */
    public function getSameAsBilling()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSameAsBilling', array());

        return parent::getSameAsBilling();
    }

    /**
     * {@inheritDoc}
     */
    public function getEcomCustomerId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEcomCustomerId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcomCustomerId', array());

        return parent::getEcomCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlgorithm($algorithm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlgorithm', array($algorithm));

        return parent::setAlgorithm($algorithm);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlgorithm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlgorithm', array());

        return parent::getAlgorithm();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function hashPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hashPassword', array());

        return parent::hashPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function checkPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkPassword', array($password));

        return parent::checkPassword($password);
    }

}
