                    <h5 class="widget-name"><i class="icon-table"></i>View All Vehicles</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-truck"></i>Vehicles</h6>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table-vehicles">
                                <thead>
                                    <tr>
                                        <th>Year</th>
                                        <th>Make</th>
                                        <th>Model</th>
                                        <th>Submodel</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
