<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/admin/lund/product-qa/edit/' . $this->productQaId,
    'method' => 'POST',
    'class'  => 'form-horizontal',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                    <h5 class="widget-name"><i class="icon-pencil"></i>Edit Product Q & A</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-asterisk"></i>Product Q & A Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/lund/product-qa/delete/<?php echo $this->productQaId; ?>"><b class="icon-trash"></b>Delete Product Q & A</a>
                                    </div>
                                </div>
                                <div class="well">
                                    <?php echo $this->form()->openTag($form); ?>
                                    <?php echo $this->formElement($fieldset->get('productQaId')); ?>
                                    <div class="alert alert-error margin">
                                        <span class="text">* denotes a required field</span>
                                    </div>
                                    <?php $status = $fieldset->get('status'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($status) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $status->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($status); ?>
                                            <?php echo ($this->formElementErrors($status) ? $errors->render($site) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $email = $fieldset->get('email'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($email) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $email->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($email); ?>
                                            <?php echo ($this->formElementErrors($email) ? $errors->render($email) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $name = $fieldset->get('name'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($name) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $name->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($name); ?>
                                            <?php echo ($this->formElementErrors($name) ? $errors->render($name) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $question = $fieldset->get('question'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($question) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $question->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($question); ?>
                                            <?php echo ($this->formElementErrors($question) ? $errors->render($question) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $answer = $fieldset->get('answer'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($answer) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $answer->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($answer); ?>
                                            <?php echo ($this->formElementErrors($answer) ? $errors->render($answer) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $productLine = $fieldset->get('productLine'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($productLine) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $productLine->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($productLine); ?>
                                            <?php echo ($this->formElementErrors($productLine) ? $errors->render($productLine) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $ecomCustomer = $fieldset->get('ecomCustomer'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($ecomCustomer) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $ecomCustomer->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($ecomCustomer); ?>
                                            <?php echo ($this->formElementErrors($ecomCustomer) ? $errors->render($ecomCustomer) : ''); ?>
                                        </div>
                                    </div>
                                    <div class="form-actions align-right">
                                        <button id="form-submit-btn" type="submit" class="btn btn-primary">Submit</button>
                                        <button id="form-cancel-btn" type="button" class="btn btn-danger">Cancel</button>
                                        <button id="form-reset-btn" type="reset" class="btn">Reset</button>
                                    </div>
                                    <?php echo $this->form()->closeTag($form); ?>
                                </div>
                            </div>
                        </div>
                    </div>
