                    <h5 class="widget-name"><i class="icon-table"></i>View All Product Q & A</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-asterisk"></i>Product Q & A</h6>
                                <a class="btn btn-info pull-right" href="/admin/lund/product-qa/create"><b class="icon-plus"></b>Add Product Q & A</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Status</th>
                                        <th>Question</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                    	<td><?php switch ($record->getStatus()) {
                                    				case 0 :
                                    					echo 'Published';
                                    					break;
                                    				case 1 :
                                    					echo 'Disabled';
                                    					break;
                                    				default :
                                    					echo 'Pending';
                                    					break;
                                    			} ?></td>
                                        <td><?php echo $record->getQuestion(); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/lund/product-qa/edit/<?php echo $record->getProductQaId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/lund/product-qa/view/<?php echo $record->getProductQaId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/lund/product-qa/delete/<?php echo $record->getProductQaId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
