                    <div class="row-fluid">
                        <div class="span4">
                            <div class="widget">
                                <div class="navbar-inner">
                                    <h6><i class="icon-th-large"></i>Brand Details</h6>
                                </div>
                                <div class="well-smoke">
                                    <form id="brand-form" class="form-horizontal" name="brand-form" method="POST" action="">
                                    <div class="control-group">
                                        <label class="control-label">Name</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->brand->getLabel(); ?>" readonly="" name="product-line-name"> </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">AAIA ID</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->brand->getAaiaid(); ?>" readonly="" name="product-line-name"> </div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h5 class="widget-name"><i class="icon-table"></i>View All Product Categories</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-th"></i>Product Categories</h6>
                                <a class="btn btn-info pull-right" href="/admin/products/brands/view/<?php echo $this->brandId; ?>/productcategory/create"><b class="icon-upload-alt"></b>Add Product Category</a>
                                <a class="btn btn-inverse pull-right" href="/admin/products/brands/view/<?php echo $this->brandId; ?>"><b class="icon-table"></b>Return to Brand</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Position</th>
                                        <th>Display Name</th>
                                        <th>BPCS Code</th>
                                        <th>Disabled?</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $record->getPosition(); ?></td>
                                        <td><?php echo $record->getProductCategory()->getDisplayName(); ?></td>
                                        <td><?php echo $record->getProductCategory()->getBpcsCode(); ?></td>
                                        <td><?php echo ($record->getDisabled() ? 'Yes' : 'No'); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/products/brands/view/<?php echo $this->brandId; ?>/productcategory/edit/<?php echo $record->getBrandProductCategoryId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/products/brands/view/<?php echo $this->brandId; ?>/productcategory/view/<?php echo $record->getBrandProductCategoryId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/products/brands/view/<?php echo $this->brandId; ?>/productcategory/delete/<?php echo $record->getBrandProductCategoryId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
