                    <h5 class="widget-name"><i class="icon-external-link"></i>View Brand Product Category</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-sitemap"></i>Brand Product Category Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/products/brands/view/<?php echo $this->brandId; ?>/productcategory/delete/<?php echo $this->recordId; ?>"><b class="icon-trash"></b>Delete Brand Product Category</a>
                                        <a class="btn btn-info pull-right" href="/admin/products/brands/view/<?php echo $this->brandId; ?>/productcategory/edit/<?php echo $this->recordId; ?>"><b class="icon-pencil"></b>Edit Brand Product Category</a>
                                        <a class="btn btn-inverse pull-right" href="/admin/products/brands/view/<?php echo $this->brandId; ?>/productcategory"><b class="icon-table"></b>Return to List</a>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-readonly-partial', array(
    'form' => $this->form,
));
?>
                                </div>
                            </div>
                        </div>
                    </div>
