                    <div class="row-fluid">
                        <div class="span3">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-shopping-cart"></i>Order Details</h6>
                                        <a class="btn btn-info pull-right" href="/admin/order-system/order/view/<?php echo $this->order->getOrderId(); ?>"><b class="icon-plus"></b>Return to Order</a>
                                    </div>
                                </div>
                                <div class="well-smoke">
                                    <form id="menu-form" class="form-horizontal" name="menu-form" method="POST" action="">
                                    <div class="control-group">
                                        <label class="control-label">Order ID</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->order->getOrderId(); ?>" readonly="" name="menu-title"> </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">Order Total</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->order->getTotal(); ?>" readonly="" name="menu-short-code"> </div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h5 class="widget-name"><i class="icon-table"></i>View All Order Items</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="fam-basket"></i>Items</h6>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Part Number</th>
                                        <th>Description</th>
                                        <th>Quantity</th>
                                        <th>Price (each)</th>
                                        <th>UPC</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $this->part->getPart($record->getProductId())->getPartNumber(); ?></td>
                                        <td><?php echo $record->getDescription(); ?></td>
                                        <td><?php echo $record->getQuantity(); ?></td>
                                        <td><?php echo $record->getPrice(); ?></td>
                                        <td><?php echo $record->getUpcCode(); ?></td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
