                    <h5 class="widget-name"><i class="icon-table"></i>View All Retailers</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-th-large"></i>Retailers</h6>
                                <a class="btn btn-info pull-right" href="/admin/accounts/retailer/create"><b class="icon-plus"></b>Add New Retailer</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table-retailers">
                                <thead>
                                    <tr>
                                        <th>Company Name</th>
                                        <th>Retailer Type</th>
                                        <th>Address</th>
                                        <th>Phone Number</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
