                    <div class="row-fluid">
                        <div class="span4">
                            <div class="widget">
                                <div class="navbar-inner">
                                    <h6><i class="icon-th-list"></i>Product Line Details</h6>
                                </div>
                                <div class="well-smoke">
                                    <form id="product-line-form" class="form-horizontal" name="product-line-form" method="POST" action="">
                                    <div class="control-group">
                                        <label class="control-label">Display Name</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->productLine->getDisplayName(); ?>" readonly="" name="product-line-name"> </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">BPCS Code</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->productLine->getBpcsCode(); ?>" readonly="" name="product-line-bpcs-code"> </div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h5 class="widget-name"><i class="icon-table"></i>View All Features</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-list-ol"></i>Features</h6>
                                <a class="btn btn-info pull-right" href="/admin/products/productlines/view/<?php echo $this->productLineId; ?>/feature/create"><b class="icon-upload-alt"></b>Add Feature</a>
                                <a class="btn btn-inverse pull-right" href="/admin/products/productlines/view/<?php echo $this->productLineId; ?>"><b class="icon-table"></b>Return to Product Line</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Feature Sequence</th>
                                        <th>Adjust Sequence</th>
                                        <th>Feature Copy</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $record->getFeatureSeq(); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <?php if ($record->getFeatureSeq() != 1) { ?>
                                                <li><a href="/admin/products/productlines/view/<?php echo $this->productLineId; ?>/feature/rank-up/<?php echo $record->getProductLineFeatureId(); ?>" class="btn tip" title="Rank Up Feature"><i class="icon-arrow-up"></i></a></li>
                                                <?php } ?>
                                                <?php if ($record->getFeatureSeq() != $this->max) { ?>
                                                <li><a href="/admin/products/productlines/view/<?php echo $this->productLineId; ?>/feature/rank-down/<?php echo $record->getProductLineFeatureId(); ?>" class="btn tip" title="Rank Down Feature"><i class="icon-arrow-down"></i></a></li>
                                                <?php } ?>
                                            </ul>
                                        </td>
                                        <td><?php echo $record->getFeatureCopy(); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/products/productlines/view/<?php echo $this->productLineId; ?>/feature/edit/<?php echo $record->getProductLineFeatureId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/products/productlines/view/<?php echo $this->productLineId; ?>/feature/view/<?php echo $record->getProductLineFeatureId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/products/productlines/view/<?php echo $this->productLineId; ?>/feature/delete/<?php echo $record->getProductLineFeatureId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
