<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/admin/lund/video-testimonials/edit/' . $this->videoTestimonialsId,
    'method' => 'POST',
    'class'  => 'form-horizontal',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                    <h5 class="widget-name"><i class="icon-pencil"></i>Edit Video Testimonials</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-asterisk"></i>Video Testimonials Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/lund/video-testimonials/delete/<?php echo $this->videoTestimonialsId; ?>"><b class="icon-trash"></b>Delete Video Testimonials</a>
                                    </div>
                                </div>
                                <div class="well">
                                    <?php echo $this->form()->openTag($form); ?>
                                    <?php echo $this->formElement($fieldset->get('videoTestimonialsId')); ?>
                                    <div class="alert alert-error margin">
                                        <span class="text">* denotes a required field</span>
                                    </div>
                                    <?php $status = $fieldset->get('status'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($status) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $status->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($status); ?>
                                            <?php echo ($this->formElementErrors($status) ? $errors->render($site) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $title = $fieldset->get('title'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($title) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $title->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($title); ?>
                                            <?php echo ($this->formElementErrors($title) ? $errors->render($title) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $comment = $fieldset->get('comment'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($comment) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $comment->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($comment); ?>
                                            <?php echo ($this->formElementErrors($comment) ? $errors->render($comment) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $url = $fieldset->get('url'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($url) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $url->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($url); ?>
                                            <?php echo ($this->formElementErrors($url) ? $errors->render($url) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $productLine = $fieldset->get('productLine'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($productLine) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $productLine->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($productLine); ?>
                                            <?php echo ($this->formElementErrors($productLine) ? $errors->render($productLine) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $ecomCustomer = $fieldset->get('ecomCustomer'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($ecomCustomer) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $ecomCustomer->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($ecomCustomer); ?>
                                            <?php echo ($this->formElementErrors($ecomCustomer) ? $errors->render($ecomCustomer) : ''); ?>
                                        </div>
                                    </div>
                                    <div class="form-actions align-right">
                                        <button id="form-submit-btn" type="submit" class="btn btn-primary">Submit</button>
                                        <button id="form-cancel-btn" type="button" class="btn btn-danger">Cancel</button>
                                        <button id="form-reset-btn" type="reset" class="btn">Reset</button>
                                    </div>
                                    <?php echo $this->form()->closeTag($form); ?>
                                </div>
                            </div>
                        </div>
                    </div>
