                    <h5 class="widget-name"><i class="icon-external-link"></i>View Special Offers</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-asterisk"></i>Special Offers Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/lund/special-offers/delete/<?php echo $this->recordId; ?>"><b class="icon-trash"></b>Delete Special Offers</a>
                                        <a class="btn btn-info pull-right" href="/admin/lund/special-offers/edit/<?php echo $this->recordId; ?>"><b class="icon-pencil"></b>Edit Special Offers</a>
                                        <a class="btn btn-inverse pull-right" href="/admin/lund/special-offers"><b class="icon-table"></b>Return to List</a>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-readonly-partial', array(
    'form' => $this->form,
));
?>
                                </div>
                            </div>
                        </div>
                    </div>
