		
				<div class="col-md-9">
				
					<div class="b-submit__main">
						<header class="s-headerSubmit s-lineDownLeft wow zoomInUp" data-wow-delay="0.5s">
							<h2 class="">Affiliate Program</h2>
						</header>
							
    					<div class="col-md-12">
    						<?php for ($x = 0; $x <= count($this->retailersOnline); $x+=2) {?>
    						<div class="row">
    							<div class="col-md-6">
    								<a href="<?php echo $this->retailersOnline[$x]->getWebsite(); ?>" ><?php echo $this->retailersOnline[$x]->getCompanyName(); ?></a>
    								<br />
    								<?php echo $this->retailersOnline[$x]->getDiscountCopy(); ?>
    							</div>
    							<div class="col-md-6">
    								<?php if(array_key_exists($x+1, $this->retailersOnline)) { ?>
    									<a href="<?php echo $this->retailersOnline[$x+1]->getWebsite(); ?>" ><?php echo $this->retailersOnline[$x+1]->getCompanyName(); ?></a>
    								<br />
    								<?php echo $this->retailersOnline[$x+1]->getDiscountCopy(); ?>
    								<?php } ?>
    							</div>
    						</div>
    						<?php } ?>
    					</div>
					</div>
				</div>
				