		<div class="b-infoBar">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
						<div class="b-infoBar__progress wow zoomInUp" data-wow-delay="0.3s">
							<div class="b-infoBar__progress-line clearfix">
								<div class="b-infoBar__progress-line-step m-active">
									<div class="b-infoBar__progress-line-step-circle">
										<div class="b-infoBar__progress-line-step-circle-inner m-active"></div>
									</div>
								</div>
								<div class="b-infoBar__progress-line-step m-active">
									<div class="b-infoBar__progress-line-step-circle">
										<div class="b-infoBar__progress-line-step-circle-inner m-active"></div>
									</div>
								</div>
								<div class="b-infoBar__progress-line-step m-active">
									<div class="b-infoBar__progress-line-step-circle">
										<div class="b-infoBar__progress-line-step-circle-inner m-active"></div>
									</div>
								</div>
								<div class="b-infoBar__progress-line-step m-active">
									<div class="b-infoBar__progress-line-step-circle">
										<div class="b-infoBar__progress-line-step-circle-inner m-active"></div>
									</div>
									<div class="b-infoBar__progress-line-step-circle m-last">
										<div class="b-infoBar__progress-line-step-circle-inner m-active"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div><!--b-infoBar-->
		<div class="b-submit">
			<div class="container">
				<div class="row">
					<div class="col-lg-3 col-md-4 col-sm-5 col-xs-6">
						<aside class="b-submit__aside">
							<div class="b-submit__aside-step wow zoomInUp" data-wow-delay="0.5s">
								<h3>Step 1</h3>
								<div class="b-submit__aside-step-inner clearfix">
									<div class="b-submit__aside-step-inner-icon">
										<span class="fa fa-shopping-cart"></span>
									</div>
									<div class="b-submit__aside-step-inner-info">
										<h4>Shopping Cart</h4>
										<p>Manage Your Products</p>
									</div>
								</div>
							</div>
							<div class="b-submit__aside-step wow zoomInUp" data-wow-delay="0.5s">
								<h3>Step 2</h3>
								<div class="b-submit__aside-step-inner clearfix">
									<div class="b-submit__aside-step-inner-icon">
										<span class="fa fa-user"></span>
									</div>
									<div class="b-submit__aside-step-inner-info">
										<h4>Registration</h4>
										<p>Give your information</p>
									</div>
								</div>
							</div>
							<div class="b-submit__aside-step wow zoomInUp" data-wow-delay="0.5s">
								<h3>Step 3</h3>
								<div class="b-submit__aside-step-inner clearfix">
									<div class="b-submit__aside-step-inner-icon">
										<span class="fa fa-ship"></span>
									</div>
									<div class="b-submit__aside-step-inner-info">
										<h4>Billing & Shipping</h4>
										<p>Give your information</p>
									</div>
								</div>
							</div>
							<div class="b-submit__aside-step wow zoomInUp" data-wow-delay="0.5s">
								<h3>Step 4</h3>
								<div class="b-submit__aside-step-inner clearfix">
									<div class="b-submit__aside-step-inner-icon">
										<span class="fa fa-cc-visa"></span>
									</div>
									<div class="b-submit__aside-step-inner-info">
										<h4>Payment</h4>
										<p>Complete Payment</p>
									</div>
								</div>
							</div>
							<div class="b-submit__aside-step m-active">
								<h3>Step 5</h3>
								<div class="b-submit__aside-step-inner m-active  clearfix">
									<div class="b-submit__aside-step-inner-icon">
										<span class="fa fa-money"></span>
									</div>
									<div class="b-submit__aside-step-inner-info">
										<h4>Receipt</h4>
										<p>Collect your invoice</p>
										<div class="b-submit__aside-step-inner-info-triangle"></div>
									</div>
								</div>
							</div>
						</aside>
					</div>
					<div class="col-lg-9 col-md-8 col-sm-7 col-xs-6">
						<div class="b-submit__main">
							<header class="s-headerSubmit s-lineDownLeft wow zoomInUp" data-wow-delay="0.5s">
								<h2 class="">Receipt</h2>
							</header>
							<form class="s-submit clearfix" action="/" method="POST">
								<div class="row">
									<div class="panel panel-default">
                                        <div class="panel-heading">Success:</div>
                                        <div class="panel-body">
                                        	<center>
                                        		<h1><i class="fa fa-check-circle-o fa-3x" style="color:#44AB00;"></i></h1>
                                        		<h2>You have successfully finish your checkout</h2>
                                        		<p>Thanks for order.</p>
                                        	</center>
                                    	</div>
                                    </div>
									<div class="panel panel-default">
                                        <div class="panel-heading">Invoice: <a class="btn btn-xs btn-success pull-right" href="javascript:window.print();"><i class="fa fa-print"></i> Print this invoice</a></div>
                                        <div class="panel-body">
											<div class="table-responsive">
												<table class="table table-striped">
                									<h4 class="text-right"><b>INVOICE ID:</b> INV-<?php echo $this->order->getOrderId();?></h4>
                									<p class="text-right"><b>Date:</b> <?php echo date('Y-m-d'); ?>
                    									<br><b>Customer Name:</b> <?php echo $_SESSION['saved_customer']['firstName']; ?>  <?php echo $_SESSION['saved_customer']['lastName']; ?>	
                									</p>
   													<thead>
                                                        <tr>
                                                            <th>ITEM</th>
                                                            <th>QTY</th>
                                                            <th>PRICE</th>
                                                            <th>TOTAL</th>
                                                            <th> </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php foreach($this->layout()->cartItems as $cartItems) { 
                                						    $total = $total + $cartItems->getPrice();
                                						?>
                                                        <tr>
                                                            <td>
                                                				<div class="row">
                                                                    <div class="col-md-4">
                                                            			<img class="img-responsive" src="/assets/library/products/product_lines/230X230/<?php echo $cartItems->getProductLinesAsset();?>" alt="<?php echo $cartItems->getProductLinesAsset();?>" title="<?php echo $cartItems->getProductLinesAsset();?>" >
                                                            		</div>
                                                            		<div class="col-md-8">
                                                            			<h4><?php echo $cartItems->getDescription(); ?></h4>
                                                            		</div>
                                                            	</div>
                                                            </td>
                                                            <td><?php echo $cartItems->getQuantity(); ?></td>
                                                           	<td><?php echo $cartItems->getPrice(); ?></td>
                                                          	<td><?php echo $cartItems->getPrice(); ?></td>
                                                       	</tr>
                                                       	<?php } ?>
                                                        <tr>
                                                            <td colspan="3" class="text-right">SUBTOTAL</td>
                                                            <td style="width:15%;">$ <?php echo $total; ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="3" class="text-right">SHIPPING</td>
                                                            <td>$ <?php echo $this->cart->getShippingCost(); ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="3" class="text-right">TAX</td>
                                                            <td>$ 0</td>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="3" class="text-right">TOTAL</td>
                                                            <td>$ <?php echo $total + $this->cart->getShippingCost();; ?></td>
                                                        </tr>
                                                	</tbody>  
                                            	</table>
                                            </div>
                                    	</div>
                                    </div>
								</div>
								<button type="submit" class="btn m-btn pull-right">Finish<span class="fa fa-angle-right"></span></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div><!--b-submit-->