<?php
$form = $this->form;

	$form->setAttributes(array(
	    'action' => '/registration',
	    'method' => 'POST',
	    'id'     => 'forms',
	))->prepare();

$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>

				<div class="col-md-9">
					<div class="b-submit__main">
						<header class="s-headerSubmit s-lineDownLeft wow zoomInUp" data-wow-delay="0.5s">
							<h2 class="">Registration Form</h2>
						</header>
						<?php if ($this->result == 'success') { ?>
                          	<p class=" wow zoomInUp" data-wow-delay="0.5s">Thank you for registering for an account with My Auto Stores!  Please check your current email to complete registration.</p>
                          	<p>&nbsp;</p>
                        	<p>&nbsp;</p>
                   		<?php } else { ?>
        				    <?php if(isset($this->error)) {?>
        				    	<ul class="messages"  style="color:red"><li class="error-msg"><ul><li><span><?php echo $this->emailErr; ?></span></li></ul></li></ul>    
        				  	<?php } ?>
    						<?php echo $this->form()->openTag($form); ?>
        						<div class="s-submit clearfix">
        							<div class="row">
        								<div class="col-md-6 col-xs-12">
    							    		<?php $firstName = $fieldset->get('firstName'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $firstName->getLabel(); ?> <span>*</span></label>
        										<div class='s-relative'>
        											<?php echo $this->formElement($firstName); ?>
        										</div>
        									</div>
        								</div>
        								<div class="col-md-6 col-xs-12">
        									<?php $lastName = $fieldset->get('lastName'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $lastName->getLabel(); ?> <span>*</span></label>
        										<div class='s-relative'>
    							            		<?php echo $this->formElement($lastName); ?>
        										</div>
        									</div>
        								</div>
        							</div>
        							<div class="row">
        								<div class="col-md-6 col-xs-12">
    							    		<?php $billingCountry = $fieldset->get('billingCountry'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $billingCountry->getLabel(); ?><span>*</span></label>
        										<div class='s-relative'>
        											<?php echo $this->formElement($billingCountry); ?>
        										</div>
        									</div>
        								</div>
        								<div class="col-md-6 col-xs-12">
        									<?php $billingState = $fieldset->get('billingState'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $billingState->getLabel(); ?> <span>*</span></label>
        										<div class='s-relative'>
        											<?php echo $this->formElement($billingState); ?>
        										</div>
        									</div>
        								</div>
        							</div>
        							<div class="row">
        								<div class="col-md-6 col-xs-12">
    							    		<?php $phoneNumber = $fieldset->get('phoneNumber'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $phoneNumber->getLabel(); ?> <span>*</span></label>
        										<div class='s-relative'>
        											<?php echo $this->formElement($phoneNumber); ?>
        										</div>
        									</div>
        								</div>
        								<div class="col-md-6 col-xs-12">
        									<?php $email = $fieldset->get('email'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $email->getLabel(); ?> <span>*</span></label>
        										<div class='s-relative'>
        											<?php echo $this->formElement($email); ?>
        										</div>
        									</div>
        								</div>
        							</div>
        							<div class="row">
        								<div class="col-md-6 col-xs-12">
    							    		<?php $password = $fieldset->get('password'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $password->getLabel(); ?> <span>*</span></label>
        										<div class='s-relative'>
        											<?php echo $this->formElement($password); ?>
        										</div>
        									</div>
        								</div>
        								<div class="col-md-6 col-xs-12">
        									<?php $passwordVerification = $fieldset->get('passwordVerification'); ?>
        									<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
        										<label><?php echo $passwordVerification->getLabel(); ?> <span>*</span></label>
        										<div class='s-relative'>
    		                            			<?php echo $this->formElement($passwordVerification); ?>
        										</div>
        									</div>
        								</div>
        							</div>	
        							<button type="submit" class="btn m-btn pull-right">Submit<span class="fa fa-angle-right"></span></button>
        						</div>
                			<?php echo $this->form()->closeTag($form); ?>
                			
                			<?php } ?>
					</div>
				</div>
				
				<script type="text/javascript">
					jQuery(document).ready(function () {
						
		    			jQuery(".phoneNumber").mask("999-999-9999");

					});
				</script>
				
				