
					<div class="col-sm-9 col-xs-12">
						<div class="col-sm-4 col-xs-12"><a href="#" data-toggle="modal" data-target="#details1" style="text-decoration:none;">
						<div class="b-world__item" style="height:auto;">
							<img class="img-responsive" src="/assets/application/myautostores/img/media1.jpg" alt="wolks" style="height:250px;">
							<div class="b-world__item-val">
								<span class="b-world__item-val-title">1 Hours ago</span>
								
								<span class="b-world__item-num"><i class="fa fa-thumbs-up"></i> 10</span>
								<span class="b-world__item-num"><i class="fa fa-comments"></i> 1</span>
							</div>
							<h3><i class="fa fa-user"></i> Bushwacker</h3>
							<p>Curabitur libero. Donec facilisis velit eu est. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc...</p>
							
						</div></a>
					</div>
					
					
					<div class="col-sm-4 col-xs-12"><a href="#" data-toggle="modal" data-target="#details1" style="text-decoration:none;">
						<div class="b-world__item" style="height:auto;">
							<img class="img-responsive" src="/assets/application/myautostores/img/media2.jpg" alt="wolks" style="height:250px;">
							<div class="b-world__item-val">
								<span class="b-world__item-val-title">1 Hours ago</span>
								
								<span class="b-world__item-num"><i class="fa fa-thumbs-up"></i> 10</span>
								<span class="b-world__item-num"><i class="fa fa-comments"></i> 1</span>
							</div>
							<h3><i class="fa fa-user"></i> Bushwacker</h3>
							<p>Curabitur libero. Donec facilisis velit eu est. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc...</p>
							
						</div></a>
					</div>
					
					
					<div class="col-sm-4 col-xs-12"><a href="#" data-toggle="modal" data-target="#details1" style="text-decoration:none;">
						<div class="b-world__item" style="height:auto;">
							<img class="img-responsive" src="/assets/application/myautostores/img/media3.jpg" alt="wolks" style="height:250px;">
							<div class="b-world__item-val">
								<span class="b-world__item-val-title">1 Hours ago</span>
								
								<span class="b-world__item-num"><i class="fa fa-thumbs-up"></i> 10</span>
								<span class="b-world__item-num"><i class="fa fa-comments"></i> 1</span>
							</div>
							<h3><i class="fa fa-user"></i> Bushwacker</h3>
							<p>Curabitur libero. Donec facilisis velit eu est. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc...</p>
							
						</div></a>
					</div>
					
					
					<div class="col-sm-4 col-xs-12"><a href="#" data-toggle="modal" data-target="#details1" style="text-decoration:none;">
						<div class="b-world__item" style="height:auto;">
							<img class="img-responsive" src="/assets/application/myautostores/img/homeCount.jpg" alt="wolks" style="height:250px;">
							<div class="b-world__item-val">
								<span class="b-world__item-val-title">1 Hours ago</span>
								
								<span class="b-world__item-num"><i class="fa fa-thumbs-up"></i> 10</span>
								<span class="b-world__item-num"><i class="fa fa-comments"></i> 1</span>
							</div>
							<h3><i class="fa fa-user"></i> Bushwacker</h3>
							<p>Curabitur libero. Donec facilisis velit eu est. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc...</p>
							
						</div></a>
					</div>
					
					<div class="col-sm-4 col-xs-12"><a href="#" data-toggle="modal" data-target="#details1" style="text-decoration:none;">
						<div class="b-world__item" style="height:auto;">
							<img class="img-responsive" src="/assets/application/myautostores/img/media1.jpg" alt="wolks" style="height:250px;">
							<div class="b-world__item-val">
								<span class="b-world__item-val-title">1 Hours ago</span>
								
								<span class="b-world__item-num"><i class="fa fa-thumbs-up"></i> 10</span>
								<span class="b-world__item-num"><i class="fa fa-comments"></i> 1</span>
							</div>
							<h3><i class="fa fa-user"></i> Bushwacker</h3>
							<p>Curabitur libero. Donec facilisis velit eu est. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc...</p>
							
						</div></a>
					</div>
					</div>