		<section class="b-pageHeader">
			<div class="container">
				<h1 class="wow zoomInLeft" data-wow-delay="0.5s"></h1>
			</div>
		</section><!--b-pageHeader-->

		<div class="b-breadCumbs s-shadow wow zoomInUp" data-wow-delay="0.5s">
			<div class="container">
				<a href="/" class="b-breadCumbs__page">Home</a><span class="fa fa-angle-right"></span>
				<a href="/products/"   class="b-breadCumbs__page"></a><span class="fa fa-angle-right"></span>
				<a href="#" class="b-breadCumbs__page m-active"></a>
			</div>
		</div><!--b-breadCumbs-->
		<!--  
		<div class="b-infoBar">
			<div class="container">
				<div class="row wow zoomInUp" data-wow-delay="0.5s">
					<div class="col-xs-3">
						<div class="b-infoBar__premium">Premium Listing</div>
					</div>
					<div class="col-xs-9">
						<div class="b-infoBar__btns">
							<a href="#" class="btn m-btn m-infoBtn"><i class="fa fa-heart"></i> ADD TO FAVOURITES<span class="fa fa-angle-right"></span></a>
							<a href="#" class="btn m-btn m-infoBtn"><i class="fa fa-print"></i> PRINT THIS PAGE<span class="fa fa-angle-right"></span></a>
							<a href="#" class="btn m-btn m-infoBtn"><i class="fa fa-download"></i> DOWNLOAD MANUAL<span class="fa fa-angle-right"></span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		-->
		<!--b-infoBar-->
		<section class="b-detail s-shadow">
			<div class="container">
				<header class="b-detail__head s-lineDownLeft wow zoomInUp" data-wow-delay="0.5s">
					<div class="row">
						<div class="col-sm-9 col-xs-12">
							<div class="b-detail__head-title">
								<h2></h2>
								<!--<h3>Fully Redesigned Upscale Midsize Car</h3>-->
							</div>
						</div>
						<div class="col-sm-3 col-xs-12">
							<div class="b-detail__head-price">
								<div class="b-detail__head-price-num">Starting at $0</div>
								
							</div>
						</div>
					</div>
				</header>
				<div class="b-detail__main">
					<div class="row">
						<div class="col-md-8 col-xs-12">
							<div class="b-detail__main-info">
								<div class="b-detail__main-info-images">
									<div class="row m-smallPadding">
										<div class="col-xs-10">
											<ul class="b-detail__main-info-images-big bxslider enable-bx-slider" data-pager-custom="#bx-pager" data-mode="horizontal" data-pager-slide="true" data-mode-pager="vertical" data-pager-qty="5">
											
        										<li class="s-relative">    
                									<img class="img-responsive center-block" src="/assets/library/products/product_lines/600X600/Jeep_FX_FF_Square.jpeg" alt="0" title="0" />
                								</li> 
                								<li class="s-relative">    
                									<img class="img-responsive center-block" src="/assets/library/products/product_lines/600X600/FX_Lifestyle.jpeg" alt="1" title="1" />
                								</li>   
                								<li class="s-relative">    
                									<img class="img-responsive center-block" src="/assets/library/products/product_lines/600X600/ex-extrawidestyle2pctexturd-1.jpeg" alt="2" title="2" />
                								</li> 
                								<li class="s-relative">    
                									<img class="img-responsive center-block" src="/assets/library/products/product_lines/600X600/ex-extrawidestyle2pctexturd-2.jpeg" alt="3" title="3" />
                								</li>
											</ul>
										</div>
										<div class="col-xs-2 pagerSlider pagerVertical">
											<div class="b-detail__main-info-images-small" id="bx-pager">
        										<a href="#" data-slide-index="0" class="b-detail__main-info-images-small-one">
        											<img class="img-responsive" src="/assets/library/products/product_lines/108X108/Jeep_FX_FF_Square.jpeg" alt="0" title="0" />
        										</a>	 
        										<a href="#" data-slide-index="1" class="b-detail__main-info-images-small-one">
        											<img class="img-responsive" src="/assets/library/products/product_lines/108X108/FX_Lifestyle.jpeg" alt="1" title="1" />
        										</a> 
        										<a href="#" data-slide-index="2" class="b-detail__main-info-images-small-one">
        											<img class="img-responsive" src="/assets/library/products/product_lines/108X108/ex-extrawidestyle2pctexturd-1.jpeg" alt="2" title="2" />
        										</a>
        										<a href="#" data-slide-index="3" class="b-detail__main-info-images-small-one">
        											<img class="img-responsive" src="/assets/library/products/product_lines/108X108/ex-extrawidestyle2pctexturd-2.jpeg" alt="3" title="3" />
        										</a>
											</div>
										</div>
									</div>
								</div>
								
    						</div>
							
						</div>
					</div>
				</div>
			</div>
		</section>									
		<section class="b-brands s-shadow">
			<div class="container">
				<h3 class="s-title">RELATED PRODUCTS</h3>
				<div id="carousel-small" class="owl-carousel enable-owl-carousel" data-items="4" data-navigation="true" data-auto-play="true" data-stop-on-hover="true" data-items-desktop="4" data-items-desktop-small="4" data-items-tablet="3" data-items-tablet-small="2">
				
					
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="/assets/library/products/product_lines/230X230/Jeep_FX_FF_Square.jpeg"  />
								<!--  
								    <span class="m-premium">Premium</span>
								-->
							</a>
							<div class="b-featured__item-price">
								
							</div>
							<div class="clearfix"></div>
							<div class="b-title">
							<h5></h5>
							</div>
							<div class="b-featured__item-links">
							</div>
						</div>
					</div>
					
					
					
				</div>
			</div>
		</section><!--b-brands-->
		