		
				<div class="col-md-9">
				
					<div class="b-submit__main">
							<header class="s-headerSubmit s-lineDownLeft wow zoomInUp" data-wow-delay="0.5s">
								<h2 class="">Track My Order</h2>
							</header>
							<form class="s-submit clearfix" action="" method="POST">
								<div class="row">
								
								
									<div class="col-md-10 col-xs-12">
										<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
											<label>Email Address <span>*</span></label>
											<div class='s-relative'>
												<input placeholder="Type here" name="email" type="text">
											</div>
										</div>
									</div>
									
									
									
									<div class="col-md-10 col-xs-12">
										<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
											<label>Order Number <span>*</span></label>
											<div class='s-relative'>
												<input placeholder="Type here" name="order-number" type="text">
											</div>
										</div>
									</div>
									
									
									
									<div class="col-md-10 col-xs-12">
										<div class="b-submit__main-element wow zoomInUp" data-wow-delay="0.5s">
											<label>Billing Zip Code <span>*</span></label>
											<div class='s-relative'>
												<input placeholder="Type here" name="zip-code" type="text">
											</div>
										</div>
									</div>
									
								</div>
								<button type="submit" class="btn m-btn">CHECK ORDER STATUS<span class="fa fa-angle-right"></span></button>
							</form>
						</div>
				
				</div>
				