                    <h5 class="widget-name"><i class="icon-table"></i>View All Reviews</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-comments"></i>Product Reviews</h6>
                                <a class="btn btn-info pull-right" href="/admin/products/productreviews/create"><b class="icon-plus"></b>Add New Review</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table-product-reviews">
                                <thead>
                                    <tr>
                                        <th>Created</th>
                                        <th>Product Line</th>
                                        <th>User</th>
                                        <th>Rating</th>
                                        <th>Review</th>
                                        <th>Disabled</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
