<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<meta name="google-site-verification" content="vwtF0jPPhuu6S9zQq5HkyJkHx2r-5xB2Hc0UBqBAgro" />
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/><title><?php echo (null !== $this->brandName? 'My Auto Stores - '.$this->brandName: ''); ?><?php echo (null !== $this->metaTitle? $this->metaTitle: ''); ?></title>
<meta name="keywords" content="<?php echo (null !== $this->brandName? $this->brandName: ''); ?><?php echo (null !== $this->metaKeywords ? $this->metaKeywords : 'My Auto Stores'); ?>" />
<meta name="description" content="<?php echo (null !== $this->brandName? $this->brandName: ''); ?><?php echo (null !== $this->metaDescription ? $this->metaDescription : 'My Auto Stores is America\'s fastest growing Turck Accessories, Jeep Accessories and Auto Accessories site with everything you need to make your call stand above the rest.'); ?>" />
<meta name="robots" content="INDEX,FOLLOW" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&amp;subset=latin,cyrillic">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Titillium+Web:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans:400,700">
<link rel="publisher" href="https://plus.google.com/111086276567522092414/">
<link itemprop="sameAs" href="https://plus.google.com/111086276567522092414/">
<link  rel="alternate" hreflang="en" href="https://www.myautostores.com/<?php echo (null !== $this->canonical ? $this->canonical : ''); ?>" />
<link rel="canonical" href="https://www.myautostores.com<?php echo (null !== $this->canonical ? '/'.$this->canonical : ''); ?>" />
<link rel="shortcut icon" type="image/x-icon" href="/assets/application/myautostores/images/favicon.png" />
<link rel="stylesheet" href="/assets/application/myautostores/css/bootstrap.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/font-awesome.min.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/theme.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/home.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/home-2.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/listings.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/detail.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/compare.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/blog.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/pages.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/submits.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/responsive.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/animate.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/site-colors.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/colors-demo.css">
<link rel="stylesheet" href="/assets/application/myautostores/css/colors.css">
<link rel="stylesheet" href="/assets/application/myautostores/assets/owl-carousel/owl.carousel.css">
<link rel="stylesheet" href="/assets/application/myautostores/assets/owl-carousel/owl.theme.css">
<link rel="stylesheet" href="/assets/application/myautostores/assets/bxslider/jquery.bxslider.css">
<link rel="stylesheet" type="text/css" href="/assets/application/myautostores/css/print.css" media="print" />
<link rel="stylesheet" id="switcher-css" type="text/css" href="/assets/application/myautostores/assets/switcher/css/switcher.css" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color1.css" title="color1" media="all" data-default-color="true" />
<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color2.css" title="color2" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color3.css" title="color3" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color4.css" title="color4" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color5.css" title="color5" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color6.css" title="color6" media="all" /> <script src="/assets/application/myautostores/js/jquery-1.11.3.min.js"></script>
<script src="/assets/application/myautostores/js/jquery.easyPaginate.js"></script>
<script type="application/ld+json">
    <?php if($this->slugtwo == 'side+window+deflectors') { ?>
        { "@context" : "http://schema.org", "@type" : "Product", "name" : "Side Window Deflectors", "image" : "https://www.myautostores.com/assets/library/products/product_lines/230X230/in-channelventvisor2pc-1.jpeg", "description" : "AVS In-Channel Ventvisor® Side Window Deflectors are designed to complete the look of your vehicle adding subtle style while maintaining the functionality you desire from a side window deflector.  The Ventvisor installs in the window channel for a streamlined appearance, but still allows fresh air to naturally circulate through open windows while keeping the rain and wind out.", "offers" : { "@type" : "Offer", "price" : "$ 35.99" } }
    <?php } else if ($this->slugtwo == 'tonneau+cover') { ?>
        { "@context" : "http://schema.org", "@type" : "Product", "name" : "Tonneau Cover", "image" : "https://www.myautostores.com/assets/library/products/product_lines/230X230/xLE-MAIN.jpeg", "description" : "The Lund Genesis Snap Tonneau is one of the truck accessories that every truck needs as there bed cover.  Featuring a low-profile design and black leather appearance premium vinyl that most tonneau covers never live up to.", "offers" : { "@type" : "Offer", "price" : "$ 262.99" } }
    <?php } else { ?>
        {"@context":"https://schema.org","@type":"WebSite","name":"My Auto Stores","url":"https://www.myautostores.com<?php echo (null !== $this->canonical ? '/'.$this->canonical : ''); ?>"}
    <?php } ?>
</script>
<!--[if lt IE 9]> <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script> <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script> <![endif]-->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-111029227-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-111029227-1');
</script>
<meta property="og:title" content="<?php echo (null !== $this->metaTitle? $this->metaTitle: ''); ?>">
<meta property="og:type" content="article">
<meta property="og:url" content="https://www.myautostores.com/<?php echo (null !== $this->canonical ? $this->canonical : ''); ?>">
<meta property="og:image" content="https://www.myautostores.com/assets/application/myautostores/images/favicon.png">
<meta property="og:description" content="<?php echo (null !== $this->brandName? $this->brandName: ''); ?><?php echo (null !== $this->metaDescription ? $this->metaDescription : 'My Auto Stores is America\'s fastest growing Turck Accessories, Jeep Accessories and Auto Accessories site with everything you need to make your call stand above the rest.'); ?>" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@rsampson">
<meta name="twitter:title" content="<?php echo (null !== $this->metaTitle? $this->metaTitle: ''); ?>">
<meta name="twitter:description" content="<?php echo (null !== $this->brandName? $this->brandName: ''); ?><?php echo (null !== $this->metaDescription ? $this->metaDescription : 'My Auto Stores is America\'s fastest growing Turck Accessories, Jeep Accessories and Auto Accessories site with everything you need to make your call stand above the rest.'); ?>">
</head>
<!--Minify by http://www.MinifyWeb.com/-->