<!DOCTYPE html>
<html>
	
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<title>MY AUTO STORES</title>
    
		<link rel="shortcut icon" type="image/x-icon" href="/assets/application/myautostores/images/favicon.png" />
    
		<link href="/assets/application/myautostores/css/master.css" rel="stylesheet">
    
        <!-- SWITCHER -->
		<link rel="stylesheet" id="switcher-css" type="text/css" href="/assets/application/myautostores/assets/switcher/css/switcher.css" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color1.css" title="color1" media="all" data-default-color="true" />
		<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color2.css" title="color2" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color3.css" title="color3" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color4.css" title="color4" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color5.css" title="color5" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="/assets/application/myautostores/assets/switcher/css/color6.css" title="color6" media="all" />
    
    
		
		<script src="/assets/application/myautostores/js/jquery-1.11.3.min.js"></script>
		<script src="/assets/application/myautostores/js/jquery.easyPaginate.js"></script>
		
	   <!--[if lt IE 9]>
            <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    		<script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    
	</head>