<!DOCTYPE html><html
lang="en"><meta
http-equiv="content-type" content="text/html;charset=UTF-8" /><head><meta
charset="utf-8"/><meta
name="viewport" content="width=device-width, initial-scale=1"/><title>My Auto Stores <?php echo (null !== $this->brandName? ' - '.$this->brandName: ''); ?> - <?php echo (null !== $this->metaTitle? $this->metaTitle: ''); ?></title><meta
name="keywords" content="<?php echo (null !== $this->brandName? $this->brandName: ''); ?> <?php echo (null !== $this->metaKeywords ? ' - '.$this->metaKeywords : 'My Auto Stores'); ?>" /><meta
name="description" content="<?php echo (null !== $this->brandName? $this->brandName: ''); ?> <?php echo (null !== $this->metaDescription ? ' - '.$this->metaDescription : 'My Auto Stores is America\'s fastest growing Turck Accessories, Jeep Accessories and Auto Accessories site with everything you need to make your call stand above the rest.'); ?>" /><meta
name="robots" content="INDEX,FOLLOW" /><link 
rel="alternate" hreflang="en" href="http://myautostores.com/" /><link
rel="canonical" href="https://www.myautostores.com/<?php echo (null !== $this->canonical ? $this->canonical : ''); ?>" /><link
rel="shortcut icon" type="image/x-icon" href="/assets/application/myautostores/images/favicon.png" /><link
rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&amp;subset=latin,cyrillic"><link
rel="stylesheet" href="https://fonts.googleapis.com/css?family=Titillium+Web:400,700"><link
rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans:400,700"><link
rel="stylesheet" href="/assets/application/myautostores/css/bootstrap.css"> <script src="/assets/application/myautostores/js/jquery-1.11.3.min.js"></script> <script src="/assets/application/myautostores/js/jquery.easyPaginate.js"></script> <!--[if lt IE 9]> <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script> <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script> <![endif]--></head>
<!--Minify by http://www.MinifyWeb.com/-->