                    <h5 class="widget-name"><i class="icon-table"></i>View All Testimonials</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-asterisk"></i>Testimonials</h6>
                                <a class="btn btn-info pull-right" href="/admin/lund/testimonial/create"><b class="icon-plus"></b>Add Testimonial</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Position</th>
                                        <th>Adjust</th>
                                        <th>Site</th>
                                        <th>Content</th>
                                        <th>Disabled</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $record->getPosition(); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <?php if ($record->getPosition() != 1) { ?>
                                                <li><a href="/admin/lund/testimonial/rank-up/<?php echo $record->getTestimonialId(); ?>" class="btn tip" title="Rank Up Testimonial"><i class="icon-arrow-up"></i></a></li>
                                                <?php } ?>
                                                <?php if ($record->getPosition() != $this->max) { ?>
                                                <li><a href="/admin/lund/testimonial/rank-down/<?php echo $record->getTestimonialId(); ?>" class="btn tip" title="Rank Down Testimonial"><i class="icon-arrow-down"></i></a></li>
                                                <?php } ?>
                                            </ul>
                                        </td>
                                        <td><?php echo $record->getSite()->getName(); ?></td>
                                        <td><pre><?php echo htmlspecialchars($record->getContent(), ENT_QUOTES); ?></pre></td>
                                        <td><?php echo ($record->getDisabled() ? 'Yes' : 'No'); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/lund/testimonial/edit/<?php echo $record->getTestimonialId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/lund/testimonial/view/<?php echo $record->getTestimonialId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/lund/testimonial/delete/<?php echo $record->getTestimonialId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
