                    <h5 class="widget-name"><i class="icon-table"></i>View All Parts</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-truck"></i>Parts</h6>
                                <a class="btn btn-inverse pull-right" href="/admin/products/parts/upload"><b class="icon-upload-alt"></b>Upload Part Assets</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table-parts">
                                <thead>
                                    <tr>
                                        <th>Part Number</th>
                                        <th>UPC</th>
                                        <th>Product Line</th>
                                        <th>Color</th>
                                        <th>MSRP Price</th>
                                        <th>I-Sheet</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
