                    <h5 class="widget-name"><i class="icon-upload-alt"></i>Upload Part Assets</h5>
                    <div class="row-fluid">
                        <div class="span8">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6>Multiple file uploader</h6>
                                        <a class="btn btn-inverse pull-right" href="/admin/products/parts/process"><b class="icon-upload-alt"></b>Process Part Assets</a>
                                    </div>
                                </div>
                                <div id="file-uploader" class="well">You browser doesn't have HTML 4 support.</div>
                            </div>
                        </div>
                        <div class="span4">
                            <div class="widget">
                                <div class="navbar"><div class="navbar-inner"><h6><i class="icon-fire"></i>Instructions</h6></div></div>
                                <div class="well body">
                                    <p>Part Asset files are uploaded into the parts/staging folder of the Digital Asset Management System.<p>
                                    <p><strong>Accepted file extensions (Image):</strong><br />
                                    <code>.jpg, .jpeg, .png, .gif, .tif</code></p>
                                    <p><strong>File naming conventions (Image):</strong><br />
                                    <code>
                                        123456_P04_HR.jpg<br />
                                        123456_P01_HR.jpg<br />
                                        123456_P01_HR_2.jpg<br />
                                        123456_P05_HR.jpg<br />
                                    </code></p>
                                    <p><strong>Accepted file extensions (Video):</strong><br />
                                    <code>.mp4, .m4v, .mov</code></p>
                                    <p><strong>File naming conventions (Video):</strong><br />
                                    <code>
                                        123456_installation.mp4<br />
                                        123456_lifestyle.mp4<br />
                                    </code></p>
                                    <p class="muted"><strong>note:</strong> Any deviation from these conventions will result in a failed part match.</p>
                                </div>
                        </div>
                    </div>
