                    <h5 class="widget-name"><i class="icon-table"></i>View Part Vehicles</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-truck"></i>Part Details</h6>
                                        <a class="btn btn-info pull-right" href="/admin/products/parts/view/<?php echo $this->recordId; ?>"><b class="icon-external-link"></b>Back to Part View</a>
                                    </div>
                                </div>
                                <div class="well">
                                    <form action="" method="post" name="vehicle-part-form" class="form-horizontal" id="vehicle-part-form">
                                    <div class="control-group"> 
                                        <label class="control-label">Part Number</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $record->getPartNumber(); ?>" readonly="" name="partNumber"></div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">Product Line</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $record->getProductLine()->getName(); ?>" readonly="" name="productLine"></div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-truck"></i>Vehicles</h6>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Year</th>
                                        <th>Make</th>
                                        <th>Model</th>
                                        <th>Submodel</th>
                                        <th>Class</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($record->getVehCollections()->toArray() as $vehicle) { ?>
                                    <tr>
                                        <td><?php echo $vehicle->getVehCollection()->getVehYear()->getName(); ?></td>
                                        <td><?php echo $vehicle->getVehCollection()->getVehMake()->getName(); ?></td>
                                        <td><?php echo $vehicle->getVehCollection()->getVehModel()->getName(); ?></td>
                                        <td><?php echo (($vehicle->getVehCollection()->getVehSubmodel()) ? $vehicle->getVehCollection()->getVehSubmodel()->getName() : ''); ?></td>
                                        <td><?php echo $vehicle->getVehCollection()->getVehModel()->getVehClass()->getName(); ?></td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
