<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                                    => __DIR__ . '/Module.php',
    'Application\Controller\Factory\IndexControllerFactory' => __DIR__ . '/src/Application/Controller/Factory/IndexControllerFactory.php',
    'Application\Controller\IndexController'                => __DIR__ . '/src/Application/Controller/IndexController.php',
    'zipcode_class'                                         => __DIR__ . '/src/Application/Library/zipcode.class.php',
);
