<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/admin/lund/product-registration/edit/' . $this->productRegistrationId,
    'method' => 'POST',
    'class'  => 'form-horizontal',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                    <h5 class="widget-name"><i class="icon-plus"></i>Edit Product Registration</h5>
                    <div class="row-fluid">
                        <div class="span8">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-asterisk"></i>Product Registration Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/lund/product-registration/delete/<?php echo $this->productRegistrationId; ?>"><b class="icon-trash"></b>Delete Product Registration</a>
                                    </div>
                                </div>
                                <div class="well">
                                    <?php echo $this->form()->openTag($form); ?>
                                    <?php echo $this->formElement($form->get('secret')); ?>
                                    <?php echo $this->formElement($fieldset->get('productRegistrationId')); ?>
                                    <div class="alert alert-error margin">
                                        <span class="text">* denotes a required field</span>
                                    </div>
                                    <?php $site = $fieldset->get('site'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($site) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $site->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($site); ?>
                                            <?php echo ($this->formElementErrors($site) ? $errors->render($site) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $title = $fieldset->get('title'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($title) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $title->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($title); ?>
                                            <?php echo ($this->formElementErrors($title) ? $errors->render($title) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $firstName = $fieldset->get('firstName'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($firstName) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $firstName->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($firstName); ?>
                                            <?php echo ($this->formElementErrors($firstName) ? $errors->render($firstName) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $middleInitial = $fieldset->get('middleInitial'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($middleInitial) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $middleInitial->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($middleInitial); ?>
                                            <?php echo ($this->formElementErrors($middleInitial) ? $errors->render($middleInitial) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $lastName = $fieldset->get('lastName'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($lastName) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $lastName->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($lastName); ?>
                                            <?php echo ($this->formElementErrors($lastName) ? $errors->render($lastName) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $emailAddress = $fieldset->get('emailAddress'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($emailAddress) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $emailAddress->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($emailAddress); ?>
                                            <?php echo ($this->formElementErrors($emailAddress) ? $errors->render($emailAddress) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $streetAddress = $fieldset->get('streetAddress'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($streetAddress) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $streetAddress->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($streetAddress); ?>
                                            <?php echo ($this->formElementErrors($streetAddress) ? $errors->render($streetAddress) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $extStreetAddress = $fieldset->get('extStreetAddress'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($extStreetAddress) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $extStreetAddress->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($extStreetAddress); ?>
                                            <?php echo ($this->formElementErrors($extStreetAddress) ? $errors->render($extStreetAddress) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $locality = $fieldset->get('locality'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($locality) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $locality->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($locality); ?>
                                            <?php echo ($this->formElementErrors($locality) ? $errors->render($locality) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $region = $fieldset->get('region'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($region) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $region->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($region); ?>
                                            <?php echo ($this->formElementErrors($region) ? $errors->render($region) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $postCode = $fieldset->get('postCode'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($postCode) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $postCode->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($postCode); ?>
                                            <?php echo ($this->formElementErrors($postCode) ? $errors->render($postCode) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $country = $fieldset->get('country'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($country) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $country->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($country); ?>
                                            <?php echo ($this->formElementErrors($country) ? $errors->render($country) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $phoneNumber = $fieldset->get('phoneNumber'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($phoneNumber) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $phoneNumber->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($phoneNumber); ?>
                                            <?php echo ($this->formElementErrors($phoneNumber) ? $errors->render($phoneNumber) : ''); ?>
                                        </div>
                                    </div>
                                <?php $birthDate = $fieldset->get('birthDate'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($birthDate) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $birthDate->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($birthDate); ?>
                                        <?php echo ($this->formElementErrors($birthDate) ? $errors->render($birthDate) : ''); ?>
                                    </div>
                                </div>
                                <?php $maritalStatus = $fieldset->get('maritalStatus'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($maritalStatus) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $maritalStatus->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($maritalStatus); ?>
                                        <?php echo ($this->formElementErrors($maritalStatus) ? $errors->render($maritalStatus) : ''); ?>
                                    </div>
                                </div>
                                <?php $productCategory = $fieldset->get('productCategory'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($productCategory) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $productCategory->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($productCategory); ?>
                                        <?php echo ($this->formElementErrors($productCategory) ? $errors->render($productCategory) : ''); ?>
                                    </div>
                                </div>
                                <?php $upcCode = $fieldset->get('upcCode'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($upcCode) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $upcCode->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($upcCode); ?>
                                        <?php echo ($this->formElementErrors($upcCode) ? $errors->render($upcCode) : ''); ?>
                                    </div>
                                </div>
                                <div class="control-group"><div class="span12">In what vehicle will this product be used?</div></div>
                                <?php $vehYear = $fieldset->get('vehYear'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($vehYear) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $vehYear->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($vehYear); ?>
                                        <?php echo ($this->formElementErrors($vehYear) ? $errors->render($vehYear) : ''); ?>
                                    </div>
                                </div>
                                <?php $vehMake = $fieldset->get('vehMake'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($vehMake) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $vehMake->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($vehMake); ?>
                                        <?php echo ($this->formElementErrors($vehMake) ? $errors->render($vehMake) : ''); ?>
                                    </div>
                                </div>
                                <?php $vehModel = $fieldset->get('vehModel'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($vehModel) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $vehModel->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($vehModel); ?>
                                        <?php echo ($this->formElementErrors($vehModel) ? $errors->render($vehModel) : ''); ?>
                                    </div>
                                </div>
                                <?php $vehSubmodel = $fieldset->get('vehSubmodel'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($vehSubmodel) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $vehSubmodel->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($vehSubmodel); ?>
                                        <?php echo ($this->formElementErrors($vehSubmodel) ? $errors->render($vehSubmodel) : ''); ?>
                                    </div>
                                </div>
                                <?php $ownedLength = $fieldset->get('ownedLength'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($ownedLength) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $ownedLength->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($ownedLength); ?>
                                        <?php echo ($this->formElementErrors($ownedLength) ? $errors->render($ownedLength) : ''); ?>
                                    </div>
                                </div>
                                <?php $installer = $fieldset->get('installer'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($installer) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $installer->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($installer); ?>
                                        <?php echo ($this->formElementErrors($installer) ? $errors->render($installer) : ''); ?>
                                    </div>
                                </div>
                                <?php $pricePaid = $fieldset->get('pricePaid'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($pricePaid) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $pricePaid->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($pricePaid); ?>
                                        <?php echo ($this->formElementErrors($pricePaid) ? $errors->render($pricePaid) : ''); ?>
                                    </div>
                                </div>
                                <?php $wherePurchased = $fieldset->get('wherePurchased'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($wherePurchased) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $wherePurchased->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($wherePurchased); ?>
                                        <?php echo ($this->formElementErrors($wherePurchased) ? $errors->render($wherePurchased) : ''); ?>
                                    </div>
                                </div>
                                <div class="control-group"><div class="span12">Where did you shop for this product: (check all that apply)</div></div>
                                <?php $shopStore = $fieldset->get('shopStore'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($shopStore) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $shopStore->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($shopStore); ?>
                                        <?php echo ($this->formElementErrors($shopStore) ? $errors->render($shopStore) : ''); ?>
                                    </div>
                                </div>
                                <?php $shopOnline = $fieldset->get('shopOnline'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($shopOnline) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $shopOnline->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($shopOnline); ?>
                                        <?php echo ($this->formElementErrors($shopOnline) ? $errors->render($shopOnline) : ''); ?>
                                    </div>
                                </div>
                                <?php $shopCatalog = $fieldset->get('shopCatalog'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($shopCatalog) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $shopCatalog->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($shopCatalog); ?>
                                        <?php echo ($this->formElementErrors($shopCatalog) ? $errors->render($shopCatalog) : ''); ?>
                                    </div>
                                </div>
                                <div class="control-group"><div class="span12">When you first started shopping for this product:</div></div>
                                <?php $brandInMind = $fieldset->get('brandInMind'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($brandInMind) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $brandInMind->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($brandInMind); ?>
                                        <?php echo ($this->formElementErrors($brandInMind) ? $errors->render($brandInMind) : ''); ?>
                                    </div>
                                </div>
                                <?php $brandPurchased = $fieldset->get('brandPurchased'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($brandPurchased) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $brandPurchased->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($brandPurchased); ?>
                                        <?php echo ($this->formElementErrors($brandPurchased) ? $errors->render($brandPurchased) : ''); ?>
                                    </div>
                                </div>
                                <div class="control-group"><div class="span12">Please indicate if the following exceeded, met or did not meet your expectations:</div></div>
                                <?php $easeOfInstallation = $fieldset->get('easeOfInstallation'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($easeOfInstallation) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $easeOfInstallation->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($easeOfInstallation); ?>
                                        <?php echo ($this->formElementErrors($easeOfInstallation) ? $errors->render($easeOfInstallation) : ''); ?>
                                    </div>
                                </div>
                                <?php $quality = $fieldset->get('quality'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($quality) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $quality->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($quality); ?>
                                        <?php echo ($this->formElementErrors($quality) ? $errors->render($quality) : ''); ?>
                                    </div>
                                </div>
                                <?php $valueOfMoney = $fieldset->get('valueOfMoney'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($valueOfMoney) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $valueOfMoney->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($valueOfMoney); ?>
                                        <?php echo ($this->formElementErrors($valueOfMoney) ? $errors->render($valueOfMoney) : ''); ?>
                                    </div>
                                </div>
                                <?php $overall = $fieldset->get('overall'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($overall) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $overall->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($overall); ?>
                                        <?php echo ($this->formElementErrors($overall) ? $errors->render($overall) : ''); ?>
                                    </div>
                                </div>
                                <?php $infReputation = $fieldset->get('infReputation'); ?>
                                <?php $infEase = $fieldset->get('infEase'); ?>
                                <?php $infDealer = $fieldset->get('infDealer'); ?>
                                <?php $infRecommendation = $fieldset->get('infRecommendation'); ?>
                                <?php $infFunctionality = $fieldset->get('infFunctionality'); ?>
                                <?php $infAvailability = $fieldset->get('infAvailability'); ?>
                                <?php $infStyle = $fieldset->get('infStyle'); ?>
                                <?php $infQuality = $fieldset->get('infQuality'); ?>
                                <?php $infWarranty = $fieldset->get('infWarranty'); ?>
                                <?php $infOther = $fieldset->get('infOther'); ?>
                                <div class="control-group">
                                    <label class="control-label">What factors most influenced this purchase?</label>
                                    <div class="controls"><?php echo $this->formElement($infReputation); ?> <?php echo $infReputation->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infEase); ?> <?php echo $infEase->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infDealer); ?> <?php echo $infDealer->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infRecommendation); ?> <?php echo $infRecommendation->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infFunctionality); ?> <?php echo $infFunctionality->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infAvailability); ?> <?php echo $infAvailability->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infStyle); ?> <?php echo $infStyle->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infQuality); ?> <?php echo $infQuality->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infWarranty); ?> <?php echo $infWarranty->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($infOther); ?> <?php echo $infOther->getLabel() ?></div>
                                </div>
                                <?php $personOneGender = $fieldset->get('personOneGender'); ?>
                                <?php $personOneAge = $fieldset->get('personOneAge'); ?>
                                <?php $personTwoGender = $fieldset->get('personTwoGender'); ?>
                                <?php $personTwoAge = $fieldset->get('personTwoAge'); ?>
                                <?php $personThreeGender = $fieldset->get('personThreeGender'); ?>
                                <?php $personThreeAge = $fieldset->get('personThreeAge'); ?>
                                <?php $personFourGender = $fieldset->get('personFourGender'); ?>
                                <?php $personFourAge = $fieldset->get('personFourAge'); ?>
                                <?php $noneHousehold = $fieldset->get('noneHousehold'); ?>
                                <?php $childUnderOne = $fieldset->get('childUnderOne'); ?>
                                <div class="control-group">
                                    <label class="control-label">Not including yourself, what is the GENDER and AGE (in years) of children and other adults living in your household?</label>
                                    <div class="controls"><?php echo $this->formElement($personOneGender); ?> <?php echo $this->formElement($personOneAge); ?> yrs.</div>

                                    <div class="controls"><?php echo $this->formElement($personTwoGender); ?> <?php echo $this->formElement($personTwoAge); ?> yrs.</div>

                                    <div class="controls"><?php echo $this->formElement($personThreeGender); ?> <?php echo $this->formElement($personThreeAge); ?> yrs.</div>

                                    <div class="controls"><?php echo $this->formElement($personFourGender); ?> <?php echo $this->formElement($personFourAge); ?> yrs.</div>
                                    <div class="controls"><?php echo $this->formElement($noneHousehold); ?> <?php echo $noneHousehold->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($childUnderOne); ?> <?php echo $childUnderOne->getLabel() ?></div>
                                </div>
                                <?php $youOccupation = $fieldset->get('youOccupation'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($youOccupation) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $youOccupation->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($youOccupation); ?>
                                        <?php echo ($this->formElementErrors($youOccupation) ? $errors->render($youOccupation) : ''); ?>
                                    </div>
                                </div>
                                <?php $spouseOccupation = $fieldset->get('spouseOccupation'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($spouseOccupation) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $spouseOccupation->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($spouseOccupation); ?>
                                        <?php echo ($this->formElementErrors($spouseOccupation) ? $errors->render($spouseOccupation) : ''); ?>
                                    </div>
                                </div>
                                <?php $youHomemaker = $fieldset->get('youHomemaker'); ?>
                                <?php $youRetired = $fieldset->get('youRetired'); ?>
                                <?php $youStudent = $fieldset->get('youStudent'); ?>
                                <?php $youOwner = $fieldset->get('youOwner'); ?>
                                <?php $youHome = $fieldset->get('youHome'); ?>
                                <?php $youMilitary = $fieldset->get('youMilitary'); ?>
                                <?php $youVeteran = $fieldset->get('youVeteran'); ?>
                                <div class="control-group">
                                    <label class="control-label">Are you?</label>
                                    <div class="controls"><?php echo $this->formElement($youHomemaker); ?> <?php echo $youHomemaker->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($youRetired); ?> <?php echo $youRetired->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($youStudent); ?> <?php echo $youStudent->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($youOwner); ?> <?php echo $youOwner->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($youHome); ?> <?php echo $youHome->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($youMilitary); ?> <?php echo $youMilitary->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($youVeteran); ?> <?php echo $youVeteran->getLabel() ?></div>
                                </div>
                                <?php $spouseHomemaker = $fieldset->get('spouseHomemaker'); ?>
                                <?php $spouseRetired = $fieldset->get('spouseRetired'); ?>
                                <?php $spouseStudent = $fieldset->get('spouseStudent'); ?>
                                <?php $spouseOwner = $fieldset->get('spouseOwner'); ?>
                                <?php $spouseHome = $fieldset->get('spouseHome'); ?>
                                <?php $spouseMilitary = $fieldset->get('spouseMilitary'); ?>
                                <?php $spouseVeteran = $fieldset->get('spouseVeteran'); ?>
                                <div class="control-group">
                                    <label class="control-label">Is your spouse?</label>
                                    <div class="controls"><?php echo $this->formElement($spouseHomemaker); ?> <?php echo $spouseHomemaker->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($spouseRetired); ?> <?php echo $spouseRetired->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($spouseStudent); ?> <?php echo $spouseStudent->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($spouseOwner); ?> <?php echo $spouseOwner->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($spouseHome); ?> <?php echo $spouseHome->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($spouseMilitary); ?> <?php echo $spouseMilitary->getLabel() ?></div>
                                    <div class="controls"><?php echo $this->formElement($spouseVeteran); ?> <?php echo $spouseVeteran->getLabel() ?></div>
                                </div>
                                <?php $income = $fieldset->get('income'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($income) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $income->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($income); ?>
                                        <?php echo ($this->formElementErrors($income) ? $errors->render($income) : ''); ?>
                                    </div>
                                </div>
                                <?php $education = $fieldset->get('education'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($education) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $education->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($education); ?>
                                        <?php echo ($this->formElementErrors($education) ? $errors->render($education) : ''); ?>
                                    </div>
                                </div>
                                <?php $creditCards = $fieldset->get('creditCards'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($creditCards) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $creditCards->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($creditCards); ?>
                                        <?php echo ($this->formElementErrors($creditCards) ? $errors->render($creditCards) : ''); ?>
                                    </div>
                                </div>
                                <?php $residence = $fieldset->get('residence'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($residence) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $residence->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($residence); ?>
                                        <?php echo ($this->formElementErrors($residence) ? $errors->render($residence) : ''); ?>
                                    </div>
                                </div>
                                <div class="control-group"><div class="span12">Please tell us how many magazines your household:</div></div>
                                <?php $magazineSubscribed = $fieldset->get('magazineSubscribed'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($magazineSubscribed) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $magazineSubscribed->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($magazineSubscribed); ?>
                                        <?php echo ($this->formElementErrors($magazineSubscribed) ? $errors->render($magazineSubscribed) : ''); ?>
                                    </div>
                                </div>
                                <?php $magazinePurchased = $fieldset->get('magazinePurchased'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($magazinePurchased) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $magazinePurchased->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($magazinePurchased); ?>
                                        <?php echo ($this->formElementErrors($magazinePurchased) ? $errors->render($magazinePurchased) : ''); ?>
                                    </div>
                                </div>
                                <div class="control-group"><div class="span12">Which of the following do you plan to do within the next 6 or 12 months?</div></div>
                                <?php $newWithin = $fieldset->get('newWithin'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($newWithin) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $newWithin->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($newWithin); ?>
                                        <?php echo ($this->formElementErrors($newWithin) ? $errors->render($newWithin) : ''); ?>
                                    </div>
                                </div>
                                <?php $usedWithin = $fieldset->get('usedWithin'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($usedWithin) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $usedWithin->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($usedWithin); ?>
                                        <?php echo ($this->formElementErrors($usedWithin) ? $errors->render($usedWithin) : ''); ?>
                                    </div>
                                </div>
                                <div class="control-group"><div class="span12">Please tell us about the newest car or truck in your household:</div></div>
                                <?php $recVehYear = $fieldset->get('recVehYear'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($recVehYear) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $recVehYear->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($recVehYear); ?>
                                        <?php echo ($this->formElementErrors($recVehYear) ? $errors->render($recVehYear) : ''); ?>
                                    </div>
                                </div>
                                <?php $recVehMake = $fieldset->get('recVehMake'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($recVehMake) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $recVehMake->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($recVehMake); ?>
                                        <?php echo ($this->formElementErrors($recVehMake) ? $errors->render($recVehMake) : ''); ?>
                                    </div>
                                </div>
                                <?php $recVehModel = $fieldset->get('recVehModel'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($recVehModel) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $recVehModel->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($recVehModel); ?>
                                        <?php echo ($this->formElementErrors($recVehModel) ? $errors->render($recVehModel) : ''); ?>
                                    </div>
                                </div>
                                <?php $recVehSubmodel = $fieldset->get('recVehSubmodel'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($recVehSubmodel) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $recVehSubmodel->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($recVehSubmodel); ?>
                                        <?php echo ($this->formElementErrors($recVehSubmodel) ? $errors->render($recVehSubmodel) : ''); ?>
                                    </div>
                                </div>
                                <?php $purchaseType = $fieldset->get('purchaseType'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($purchaseType) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $purchaseType->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($purchaseType); ?>
                                        <?php echo ($this->formElementErrors($purchaseType) ? $errors->render($purchaseType) : ''); ?>
                                    </div>
                                </div>
                                <?php $aboutHousehold = $fieldset->get('aboutHousehold'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($aboutHousehold) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $aboutHousehold->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($aboutHousehold); ?>
                                        <?php echo ($this->formElementErrors($aboutHousehold) ? $errors->render($aboutHousehold) : ''); ?>
                                    </div>
                                </div>
                                <?php $lifestyleHousehold = $fieldset->get('lifestyleHousehold'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($lifestyleHousehold) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $lifestyleHousehold->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($lifestyleHousehold); ?>
                                        <?php echo ($this->formElementErrors($lifestyleHousehold) ? $errors->render($lifestyleHousehold) : ''); ?>
                                    </div>
                                </div>
                                <?php $optout = $fieldset->get('optout'); ?>
                                <div class="control-group<?php echo ($this->formElementErrors($optout) ? ' error' : ''); ?>">
                                    <label class="control-label"><?php echo $optout->getLabel() ?></label>
                                    <div class="controls">
                                        <?php echo $this->formElement($optout); ?>
                                        <?php echo ($this->formElementErrors($optout) ? $errors->render($optout) : ''); ?>
                                    </div>
                                </div>
                                <div class="form-actions align-right">
                                        <button id="form-submit-btn" type="submit" class="btn btn-primary">Submit</button>
                                        <button id="form-cancel-btn" type="button" class="btn btn-danger">Cancel</button>
                                        <button id="form-reset-btn" type="reset" class="btn">Reset</button>
                                    </div>
                                    <?php echo $this->form()->closeTag($form); ?>
                                </div>
                            </div>
                        </div>
                    </div>
