                    <h5 class="widget-name"><i class="icon-pencil"></i>Edit Product Line</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-th-list"></i>Product Line Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/products/productlines/delete/<?php echo $this->recordId; ?>"><b class="icon-trash"></b>Delete Product Line</a>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-partial', array(
    'form'     => $this->form,
    'url'      => '/admin/products/productlines/edit/' . $this->recordId,
    'fieldset' => 'product-line-fieldset',
));
?>
                                </div>
                            </div>
                        </div>
                    </div>
