                    <h5 class="widget-name"><i class="icon-plus"></i>Create a New Comparison Chart</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner"><h6><i class="icon-th-list"></i>Comparison Chart Details</h6></div>
                                </div>
                                <div class="well">
								<?php
								echo $this->partial('admin/form-partial', array(
								    'form'     => $this->form,
								    'url'      => '/admin/lund/comparison-chart/create',
								    'fieldset' => 'comparison-chart-fieldset',
								));
								?>
                                </div>
                            </div>
                        </div>
                    </div>
