                    <h5 class="widget-name"><i class="icon-external-link"></i>View Comparison Chart</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-th-list"></i>Comparison Chart Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/lund/comparison-chart/delete/<?php echo $this->recordId; ?>"><b class="icon-trash"></b>Delete Comparison Chart</a>
                                        <a class="btn btn-info pull-right" href="/admin/lund/comparison-chart/edit/<?php echo $this->recordId; ?>"><b class="icon-pencil"></b>Edit Comparison Chart</a>
                                        <a class="btn btn-inverse pull-right" href="/admin/lund/comparison-chart"><b class="icon-table"></b>Return to List</a>
                                    </div>
                                </div>
                                <div class="well">
								<?php
								echo $this->partial('admin/form-readonly-partial', array(
								    'form'     => $this->form,
								    'fieldset' => 'comparison-chart-fieldset',
								));
								?>
                                </div>
                            </div>
                        </div>
                    </div>
