                    <h5 class="widget-name"><i class="icon-table"></i>View All Support Requests</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-asterisk"></i>Support Requests</h6>
                                <a class="btn btn-info pull-right" href="/admin/lund/support-request/create"><b class="icon-plus"></b>Add Support Request</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Site</th>
                                        <th>Name</th>
                                        <th>Email Address</th>
                                        <th>Part Number</th>
                                        <th>Vehicle</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $record->getCreatedAt()->format('Y-m-d'); ?></td>
                                        <td><?php echo $record->getSite()->getName(); ?></td>
                                        <td><?php echo $record->getFirstName(); ?> <?php echo $record->getLastName(); ?></td>
                                        <td><?php echo $record->getEmailAddress(); ?></td>
                                        <td><?php echo $record->getPartNumber(); ?></td>
                                        <td><?php echo $record->getVehicle(); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/lund/support-request/edit/<?php echo $record->getSupportRequestId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/lund/support-request/view/<?php echo $record->getSupportRequestId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/lund/support-request/delete/<?php echo $record->getSupportRequestId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
