                    <h5 class="widget-name"><i class="icon-table"></i>View All News Releases</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-asterisk"></i>News Releases</h6>
                                <a class="btn btn-info pull-right" href="/admin/lund/news-release/create"><b class="icon-plus"></b>Add News Release</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Site</th>
                                        <th>News Type</th>
                                        <th>Title</th>
                                        <th>URL</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $record->getDisplayDate()->format('Y-m-d'); ?></td>
                                        <td><?php echo $record->getSite()->getName(); ?></td>
                                        <td><?php echo $record->getNewsType(); ?></td>
                                        <td><?php echo $record->getTitle(); ?></td>
                                        <td><?php echo $record->getUrl(); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/lund/news-release/edit/<?php echo $record->getNewsReleaseId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/lund/news-release/view/<?php echo $record->getNewsReleaseId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/lund/news-release/delete/<?php echo $record->getNewsReleaseId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
