<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/admin/lund/customer-review/create',
    'method' => 'POST',
    'class'  => 'form-horizontal',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                    <h5 class="widget-name"><i class="icon-plus"></i>Create a Customer Review</h5>
                    <div class="row-fluid">
                        <div class="span8">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner"><h6><i class="icon-asterisk"></i>Customer Review Details</h6></div>
                                </div>
                                <div class="well">
                                    <?php echo $this->form()->openTag($form); ?>
                                    <div class="alert alert-error margin">
                                        <span class="text">* denotes a required field</span>
                                    </div>
                                    <?php $status = $fieldset->get('status'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($status) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $status->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($status); ?>
                                            <?php echo ($this->formElementErrors($status) ? $errors->render($site) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $price = $fieldset->get('price'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($price) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $price->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($price); ?>
                                            <?php echo ($this->formElementErrors($price) ? $errors->render($price) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $value = $fieldset->get('value'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($value) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $value->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($value); ?>
                                            <?php echo ($this->formElementErrors($value) ? $errors->render($value) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $quality = $fieldset->get('quality'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($quality) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $quality->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($quality); ?>
                                            <?php echo ($this->formElementErrors($quality) ? $errors->render($quality) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $summary = $fieldset->get('summary'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($summary) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $summary->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($summary); ?>
                                            <?php echo ($this->formElementErrors($summary) ? $errors->render($summary) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $review = $fieldset->get('review'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($review) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $review->getLabel() ?><span class="text-error">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($review); ?>
                                            <?php echo ($this->formElementErrors($review) ? $errors->render($review) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $productLine = $fieldset->get('productLine'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($productLine) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $productLine->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($productLine); ?>
                                            <?php echo ($this->formElementErrors($productLine) ? $errors->render($productLine) : ''); ?>
                                        </div>
                                    </div>
                                    <?php $ecomCustomer = $fieldset->get('ecomCustomer'); ?>
                                    <div class="control-group<?php echo ($this->formElementErrors($ecomCustomer) ? ' error' : ''); ?>">
                                        <label class="control-label"><?php echo $ecomCustomer->getLabel() ?></label>
                                        <div class="controls">
                                            <?php echo $this->formElement($ecomCustomer); ?>
                                            <?php echo ($this->formElementErrors($ecomCustomer) ? $errors->render($ecomCustomer) : ''); ?>
                                        </div>
                                    </div>
                                    <div class="form-actions align-right">
                                        <button id="form-submit-btn" type="submit" class="btn btn-primary">Submit</button>
                                        <button id="form-cancel-btn" type="button" class="btn btn-danger">Cancel</button>
                                        <button id="form-reset-btn" type="reset" class="btn">Reset</button>
                                    </div>
                                    <?php echo $this->form()->closeTag($form); ?>
                                </div>
                            </div>
                        </div>
                    </div>
