    
    	<section class="b-slider"> 
			<div id="carousel" class="slide carousel carousel-fade">
				<div class="carousel-inner">
					<div class="item active">
						<img src="assets/application/myautostores/media/main-slider/1.jpg" alt="sliderImg" />
						<div class="container">
							<div class="carousel-caption b-slider__info">
								<h4>CREATE IT</h4>
								<p>Create your <span>DREAM</span> vehicle</p>
								<a class="btn m-btn" href="about.php">see details<span class="fa fa-angle-right"></span></a>
							</div>
						</div>
					</div>
					<div class="item">
						<img src="assets/application/myautostores/media/main-slider/2.jpg" alt="sliderImg" />
						<div class="container">
							<div class="carousel-caption b-slider__info">
								<h4>EXPERIENCE IT</h4>
								<p>Find your <span>DREAM</span></p>
								<a class="btn m-btn" href="about-us">see details<span class="fa fa-angle-right"></span></a>
							</div>
						</div>
					</div>
				</div>
				<a class="carousel-control right" href="#carousel" data-slide="next">
					<span class="fa fa-angle-right m-control-right"></span>
				</a>
				<a class="carousel-control left" href="#carousel" data-slide="prev">
					<span class="fa fa-angle-left m-control-left"></span>
				</a>
			</div>
		</section>
		<!--b-slider-->
		<section class="b-search">
			<div class="container">
				<form action="/products/vehicle" method="POST" class="b-search__main" id="vehicleForm" style="border-radius: 15px 15px 0 0;" onsubmit="return validateForm()" >					
					<div class="b-search__main-form wow">
						<div class="row">
							<div class="col-xs-12 col-md-12">
								<div class="m-firstSelects">
									<div class="col-xs-3">
										<select name="year" id="year"  required>
											<option value="" >   Select Year   </option>
                                   	 		<?php foreach($this->years as $year) {?>
												<option value="<?php echo $year['name']; ?>"><?php echo $year['name']; ?></option>
											<?php } ?>
										</select>
										<span class="fa fa-caret-down"></span>
									</div>
									<div class="col-xs-3">
										<select name="make" id="make" required>
											<option value="" >   Select Make   </option>
										</select>
										<span class="fa fa-caret-down"></span>
									</div>
									<div class="col-xs-3">
										<select name="model" id="model" required>
											<option value="">   Select Model   </option>
										</select>
										<span class="fa fa-caret-down"></span>
									</div>
									<div class="col-xs-3">
										<select name="price" id="price">
											<option value="">Any Price</option>
										</select>
										<span class="fa fa-caret-down"></span>
									</div>
									<input type="hidden" name="vehicle" id=vehicle value="1" />
								</div>
							</div>
							<div class="col-md-7 col-xs-12 text-left s-noPadding">
								<div class="b-search__main-form-submit">
									<button type="submit" name="submitLookup" id="submitLookup" class="btn m-btn">Go for Search<span class="fa fa-search"></span></button>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</section>
		<!--b-search-->
		<section class="b-featured">
			<div class="container">
				<h2 class="s-title">FEATURED PRODUCTS</h2>
				<div id="carousel-small" class="owl-carousel enable-owl-carousel" data-items="4" data-navigation="true" data-auto-play="true" data-stop-on-hover="true" data-items-desktop="4" data-items-desktop-small="4" data-items-tablet="3" data-items-tablet-small="2">					
					<?php 
					for($x=0; $x<count($this->upsale); $x++) { ?>
					
					<div>
						<div class="b-featured__item">
							<a href="/products/<?php echo urlencode(strtolower($this->upsale[$x]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x]['PL_Display'])); ?>">
								<img src="/assets/library/products/product_lines/<?php echo $this->upsale[$x]['fileName']?>" alt='<?php echo $this->upsale[$x]['PL_Display']; ?>' title='<?php echo $this->upsale[$x]['PL_Display']; ?>' />
								<!--  
								    <span class="m-premium">Premium</span>
								-->
							</a>
							<div class="b-featured__item-price">
								<a href="/products/<?php echo urlencode(strtolower($this->upsale[$x]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x]['PL_Display'])); ?>">
									<?php echo $this->upsale[$x]['sale_price']; ?>
								</a>
							</div>
							<div class="clearfix"></div>
							<div class="b-title">
							<h5><a href="/products/<?php echo urlencode(strtolower($this->upsale[$x]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x]['PL_Display'])); ?>"><?php echo $this->upsale[$x]['PL_Display']; ?></a></h5>
							</div>
							<div class="b-featured__item-links">
								<a href="/products/<?php echo urlencode(strtolower($this->upsale[$x]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x]['PL_Display'])); ?>"><?php echo $this->upsale[$x]['teaser'];?></a>
							</div>
						</div>
						<br />
						<div class="b-featured__item">
							<a href="/products/<?php echo urlencode(strtolower($this->upsale[$x+1]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x+1]['PL_Display'])); ?>">
								<img src="/assets/library/products/product_lines/<?php echo $this->upsale[$x+1]['fileName']?>" alt='<?php echo $this->upsale[$x+1]['PL_Display']; ?>' title='<?php echo $this->upsale[$x+1]['PL_Display']; ?>' />
								<!--  
								    <span class="m-premium">Premium</span>
								-->
							</a>
							<div class="b-featured__item-price">
								<a href="/products/<?php echo urlencode(strtolower($this->upsale[$x+1]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x+1]['PL_Display'])); ?>">
									<?php echo $this->upsale[$x+1]['sale_price']; ?>
								</a>
							</div>
							<div class="clearfix"></div>
							<div class="b-title">
							<h5><a href="/products/<?php echo urlencode(strtolower($this->upsale[$x+1]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x+1]['PL_Display'])); ?>"><?php echo $this->upsale[$x+1]['PL_Display']; ?></a></h5>
							</div>
							<div class="b-featured__item-links">
								<a href="/products/<?php echo urlencode(strtolower($this->upsale[$x+1]['PC_Display'])); ?>/<?php echo urlencode(strtolower($this->upsale[$x+1]['PL_Display'])); ?>"><?php echo $this->upsale[$x+1]['teaser'];?></a>
							</div>
						</div>
						
					</div>
					
					<?php 
					$x++;
					} ?>
					
				</div>
			</div>
		</section>
		<!--b-featured-->
		<section class="b-welcome">
			<div class="container">
				<div class="row">
					<div class="col-md-5 col-md-offset-2 col-sm-6 col-xs-12">
						<div class="b-welcome__text wow fadeInLeft" data-wow-delay="0.3s" data-wow-offset="100">
							<h2>WORLD'S BEST CAR PARTS DEALER</h2>
							<h1>WELCOME TO MYAUTOSTORES</h1>
							<p>Curabitur libero. Donec facilisis velit eudsl est. Phasellus consequat. Aenean vita quam. Vivamus et nunc. Nunc consequat sem velde metus imperdiet lacinia. Dui estter neque molestie necd dignissim ac hendrerit quis purus. Etiam sit amet vec convallis massa scelerisque mattis. Sed placerat leo nec.</p>
							<p>Ipsum midne ultrices magn eu tempor quam dolor eustrl sem. Donec quis dolel Donec pede quam placerat alterl tristique faucibus posuere lobortis.</p>
							<ul>
								<li><span class="fa fa-check"></span>Donec facilisis velit eu est phasellus consequat </li>
								<li><span class="fa fa-check"></span>Aenean vitae quam. Vivamus et nunc nunc consequat</li>
								<li><span class="fa fa-check"></span>Sem vel metus imperdiet lacinia enean </li>
								<li><span class="fa fa-check"></span>Dapibus aliquam augue fusce eleifend quisque tels</li>
							</ul>
						</div>
					</div>
					<div class="col-md-5 col-sm-6 col-xs-12">
						<div class="b-welcome__services wow fadeInRight" data-wow-delay="0.3s" data-wow-offset="100">
							<div class="row">
								<div class="col-xs-6 m-padding">
									<div class="b-welcome__services-auto">
										<div class="b-welcome__services-img m-auto">
											<span class="fa fa-cab"></span>
										</div>
										<h3>browse by vehicle</h3>
									</div>
								</div>
								<a href="/news" >
    								<div class="col-xs-6 m-padding">
    									<div class="b-welcome__services-trade">
    										<div class="b-welcome__services-img m-trade">
    											<span class="fa fa-male"></span>
    										</div>
    										<h3>News</h3>
    									</div>
    								</div>
								</a>
								<div class="col-xs-12 text-center">
									<span class="b-welcome__services-circle"></span>
								</div>
								<a href="/installation-guide" >
    								<div class="col-xs-6 m-padding">
    									<div class="b-welcome__services-buying">
    										<div class="b-welcome__services-img m-buying">
    											<span class="fa fa-book"></span>
    										</div>
    										<h3>Installation guide</h3>
    									</div>
    								</div>
								</a>
								<div class="col-xs-6 m-padding">
									<div class="b-welcome__services-support">
										<div class="b-welcome__services-img m-support">
											<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
												width="45px" height="45px" viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;" xml:space="preserve">
												<g>
													<path d="M257.938,336.072c0,17.355-14.068,31.424-31.423,31.424c-17.354,0-31.422-14.068-31.422-31.424
														c0-17.354,14.068-31.423,31.422-31.423C243.87,304.65,257.938,318.719,257.938,336.072z M385.485,304.65
														c-17.354,0-31.423,14.068-31.423,31.424c0,17.354,14.069,31.422,31.423,31.422c17.354,0,31.424-14.068,31.424-31.422
														C416.908,318.719,402.84,304.65,385.485,304.65z M612,318.557v59.719c0,29.982-24.305,54.287-54.288,54.287h-39.394
														C479.283,540.947,379.604,606.412,306,606.412s-173.283-65.465-212.318-173.85H54.288C24.305,432.562,0,408.258,0,378.275v-59.719
														c0-20.631,11.511-38.573,28.46-47.758c0.569-84.785,25.28-151.002,73.553-196.779C149.895,28.613,218.526,5.588,306,5.588
														c87.474,0,156.105,23.025,203.987,68.43c48.272,45.777,72.982,111.995,73.553,196.779C600.489,279.983,612,297.925,612,318.557z
														M497.099,336.271c0-13.969-0.715-27.094-1.771-39.812c-24.093-22.043-67.832-38.769-123.033-44.984
														c7.248,8.15,13.509,18.871,17.306,32.983c-33.812-26.637-100.181-20.297-150.382-79.905c-2.878-3.329-5.367-6.51-7.519-9.417
														c-0.025-0.035-0.053-0.062-0.078-0.096l0.006,0.002c-8.931-12.078-11.976-19.262-12.146-11.31
														c-1.473,68.513-50.034,121.925-103.958,129.46c-0.341,7.535-0.62,15.143-0.62,23.08c0,28.959,4.729,55.352,12.769,79.137
														c30.29,36.537,80.312,46.854,124.586,49.59c8.219-13.076,26.66-22.205,48.136-22.205c29.117,0,52.72,16.754,52.72,37.424
														c0,20.668-23.604,37.422-52.72,37.422c-22.397,0-41.483-9.93-49.122-23.912c-30.943-1.799-64.959-7.074-95.276-21.391
														C198.631,535.18,264.725,568.41,306,568.41C370.859,568.41,497.099,486.475,497.099,336.271z M550.855,264.269
														C547.4,116.318,462.951,38.162,306,38.162S64.601,116.318,61.145,264.269h20.887c7.637-49.867,23.778-90.878,48.285-122.412
														C169.37,91.609,228.478,66.13,306,66.13c77.522,0,136.63,25.479,175.685,75.727c24.505,31.533,40.647,72.545,48.284,122.412
														H550.855L550.855,264.269z"/>
												</g>
											</svg>
										</div>
										<h3>support</h3>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--b-asks-->
		<section class="b-featured">
			<div class="container">
				<h2 class="s-title">World's Leading Brands</h2>
				<div id="carousel-small" class="owl-carousel enable-owl-carousel" data-items="4" data-navigation="true" data-auto-play="true" data-stop-on-hover="true" data-items-desktop="4" data-items-desktop-small="4" data-items-tablet="3" data-items-tablet-small="2">
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/amp-logo.png" alt="amp research" title="amp research" style="height:35px;">
							</a>
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/avs-logo.png" alt="AVS" title="AVS" style="height:35px;">
							</a>
							
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/bushwacker-logo.png" alt="bushwacker" title="bushwacker" style="height:35px;">
							</a>
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/lund-logo.png" alt="lund" title="lund" style="height:35px;">
							</a>
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/lundinternational-logo.png" alt="lund international" title="lund international" style="height:35px;">
							</a>
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/brands-logo-rampage.png" alt="rampage" title="rampage" style="width:100px; height:35px;">
							</a>
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/rollnlock-logo.png" alt="roll n lock" title="roll n lock" style="height:35px;">
							</a>
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/stampede-logo.png" alt="stampede" title="stampede" style="height:35px;">
							</a>
						</div>
					</div>
					<div>
						<div class="b-featured__item">
							<a href="">
								<img src="assets/application/myautostores/img/tonnopro-logo.png" alt="tonnopro" title="tonnopro" style="height:35px;">
							</a>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--b-featured-->
		<section class="b-count">
			<div class="container">
				<div class="row">
					<div class="col-md-11 col-xs-12 percent-blocks m-main" data-waypoint-scroll="true">
						<div class="row">
							<div class="col-sm-3 col-xs-6">
								<div class="b-count__item">
									<div class="b-count__item-circle">
										<span class="fa fa-car"></span>
									</div>
									<div class="chart" data-percent="5000">
										<h2 class="percent">5000</h2>
									</div>
									<h5>parts to order</h5>
								</div>
							</div>
							<div class="col-sm-3 col-xs-6">
								<div class="b-count__item">
									<div class="b-count__item-circle">
										<span class="fa fa-users"></span>
									</div>
									<div class="chart" data-percent="3100">
										<h2 class="percent">3100</h2>
									</div>
									<h5>HAPPY CUSTOMER REVIEWS</h5>
								</div>
							</div>
							<div class="col-sm-3 col-xs-6">
								<div class="b-count__item">
									<div class="b-count__item-circle">
										<span class="fa fa-building-o"></span>
									</div>
									<div class="chart" data-percent="10">
										<h2 class="percent">10</h2>
									</div>
									<h5>DEALER Brands</h5>
								</div>
							</div>
							<div class="col-sm-3 col-xs-6">
								<div class="b-count__item j-last">
									<div class="b-count__item-circle">
										<span class="fa fa-suitcase"></span>
									</div>
									<div class="chart" data-percent="100">
										<h2 class="percent">100</h2>
									</div>
									<h5>FREE PARTS GIVEN</h5>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--b-count-->
		<section class="b-contact">
			<div class="container">
				<div class="row wow zoomInLeft" data-wow-delay="0.3s" data-wow-offset="100">
					<div class="col-xs-4">
						<div class="b-contact-title">
							<h5>LATEST NEWS &amp; DEALS</h5><br />
							<h3>NEWSLETTER SIGNUP</h3>
						</div>
					</div>
					<div class="col-xs-8">
						<div class="b-contact__form">
							<p>WE SEND GREAT DEALS AND LATEST AUTO NEWS TO OUR SUBSCRIBED USERS EVERY WEEK. ITS FREE SO SUBSCRIBE TODAY!</p>
							<form action="http://templines.rocks/" method="POST">
								<div><span class="fa fa-user"></span><input type="text" name="user" value="" placeholder="Your Name" /></div>
								<div><span class="fa fa-envelope"></span><input type="text" name="email" value="" placeholder="Your Email" /></div>
								<button type="submit"><span class="fa fa-angle-right"></span></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--b-contact-->
		<section class="b-review" style="background:url('assets/application/myautostores/images/backgrounds/reviews.jpg');">
			<div class="container">
				<div class="col-sm-10 col-sm-offset-1 col-xs-12" style="background:rgba(255,255,255,0.7); border-radius:10px;">
					<div id="carousel-small-rev" class="owl-carousel enable-owl-carousel" data-items="1" data-navigation="true" data-auto-play="true" data-stop-on-hover="true" data-items-desktop="1" data-items-desktop-small="1" data-items-tablet="1" data-items-tablet-small="1">
						<div class="b-review__main">
							<div class="b-review__main-person">
								<div class="b-review__main-person-inside">
								</div>
							</div><br>
							<h5><span>DONALD BROOKS</span>, Customer, Ferrari 488 GTB 2 Owner<em>"</em></h5>
							<p>Donec facilisis velit eust. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc. Nunc consequsem
								velde metus imperdiet lacinia.  Nam rutrum congue diam. Vestibulum acda risus eros auctor egestas. Morbids sem magna, viverra quis sollicitudin quis consectetuer quis nec magna.</p>
						</div>
						<div class="b-review__main">
							<div class="b-review__main-person">
								<div class="b-review__main-person-inside">
								</div>
							</div>
							<h5><span>DONALD BROOKS</span>, Customer, Ferrari 488 GTB 2 Owner<em>"</em></h5>
							<p>Donec facilisis velit eust. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc. Nunc consequsem
								velde metus imperdiet lacinia.  Nam rutrum congue diam. Vestibulum acda risus eros auctor egestas. Morbids sem magna, viverra quis sollicitudin quis consectetuer quis nec magna.</p>
						</div>
						<div class="b-review__main">
							<div class="b-review__main-person">
								<div class="b-review__main-person-inside">
								</div>
							</div>
							<h5><span>DONALD BROOKS</span>, Customer, Ferrari 488 GTB 2 Owner<em>"</em></h5>
							<p>Donec facilisis velit eust. Phasellus cons quat. Aenean vitae quam. Vivamus et nunc. Nunc consequsem
								velde metus imperdiet lacinia.  Nam rutrum congue diam. Vestibulum acda risus eros auctor egestas. Morbids sem magna, viverra quis sollicitudin quis consectetuer quis nec magna.</p>
						</div>
					</div>
				</div>
			</div>
		</section><!--b-review-->
		
		<script type="text/javascript">
								
			jQuery(document).ready(function () {

				jQuery('#year').on('change', function () {

					var year = this.value;

					jQuery('#make').attr('disabled', "");
					jQuery('#model').attr('disabled', "");
					jQuery('#price').attr('disabled', "");

					jQuery('#make').attr('required', 'required');
					jQuery('#model').attr('required', 'required');


					var data = {module : 'getMake', vehYear : year}

					jQuery.ajax({
						url: "/ajax-vehicleSelector",
						type: 'POST',
						dataType: 'json',
						data: data,
						success: function(res) {
							var $secondChoice = jQuery("#make");
							$secondChoice.empty();
							$secondChoice.append("<option value='false'>Select Make</option>");
							$.each(res, function(index, value){
											
								$.each(value, function(key2, value2 )
								{
									$secondChoice.append("<option value='" + value2 + "'>" + value2 + "</option>");
								});
							});
							jQuery('#make').removeAttr('disabled');
						},
						error: function(){
	
							alert("An error occurred Please re-select");
						}
					});
				});


				jQuery('#make').on('change', function(){

					var year = jQuery('#year').val();
		            var make = this.value;

		            jQuery("#model").empty();
					jQuery('#model').attr('required', 'required');

					var data = {module : 'getModelSubmodel', vehYear : year, vehMake : make}
					
					jQuery.ajax({
				        url: "/ajax-vehicleSelector",
			            type: 'POST',
			            dataType: 'json',
			            data: data,
				   		success: function(res) {
							var $thirdChoice = jQuery("#model");
					   		$thirdChoice.empty();
							$thirdChoice.append("<option value='false'>Select Model</option>");
				   			$.each(res, function(index, value){
					   			

					   			$.each(value, function(key2, value2 )
								{
									$thirdChoice.append("<option value='" + value2 + "'>" + value2 + "</option>");
								});
			                });

					   		jQuery('#model').removeAttr('disabled');
					   		jQuery('#make').attr('style', "border-radius: 30px; border:#eeeeee 1px solid;");
					    },
				    	error: function(){
					        alert("An error occurred Please re-select");
				    	}
				    }); 
				});


				jQuery('#model').on('change', function(){

					var $forthChoice = jQuery("#price");
			   		$forthChoice.empty();
					$forthChoice.append("<option value='0-10000'>Any Price</option>");
					$forthChoice.append("<option value='0-20'>UNDER $20.00</option>");
					$forthChoice.append("<option value='20-40'>$20.00 - $40.00</option>");
					$forthChoice.append("<option value='40-60'>$40.00 - $60.00</option>");
					$forthChoice.append("<option value='60-80'>$60.00 - $80.00</option>");
					$forthChoice.append("<option value='80-100'>$80.00 - $100.00</option>");
					$forthChoice.append("<option value='100-10000'>$100.00 OVER</option>");
					
					jQuery('#price').removeAttr('disabled');
			   		jQuery('#model').attr('style', "border-radius: 30px; border:#eeeeee 1px solid;");
					
				});

				$("form").submit(function(){

					var valid = true;
					var year = jQuery('#year').val();
					var make = jQuery('#make').val();
					var model = jQuery('#model').val();

					if('false' == make) {
						$('#make').attr('style', "border-radius: 30px; border:#FF0000 1px solid;");
				    	valid = false;
					}
					
					if('false' == model) {
						$('#model').attr('style', "border-radius: 30px; border:#FF0000 1px solid;");
				    	valid = false;
					}

					if('' == make) {
						$('#make').attr('style', "border-radius: 30px; border:#FF0000 1px solid;");
				    	valid = false;
					}

					if('' == model) {
						$('#model').attr('style', "border-radius: 30px; border:#FF0000 1px solid;");
				    	valid = false;
					}

					if(valid){
						return true;
					} else {
				    	return false;
					}
				});
				
			});

		</script>	