                    <h5 class="widget-name"><i class="icon-table"></i>View All Customers</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-th-large"></i>Customers</h6>
                                <a class="btn btn-info pull-right" href="/admin/accounts/customer/create"><b class="icon-plus"></b>Add New Customer</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Contact Name</th>
                                        <th>Update Type</th>
                                        <th>Frequency</th>
                                        <th>Last Update</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $record->getName(); ?> (<?php echo $record->getCustId(); ?>)</td>
                                        <td><?php echo $record->getEmail(); ?></td>
                                        <td><?php echo $record->getContactName(); ?></td>
                                        <td><?php echo $record->getUpdateType(); ?></td>
                                        <td><?php echo $record->getFrequency(); ?></td>
                                        <td><?php echo $this->dateFormat($record->getLastUpdate(), IntlDateFormatter::LONG, IntlDateFormatter::LONG, 'en_us'); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/accounts/customer/edit/<?php echo $record->getCustomerId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/accounts/customer/view/<?php echo $record->getCustomerId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/accounts/customer/delete/<?php echo $record->getCustomerId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
