                    <div class="row-fluid">
                        <div class="span4">
                            <div class="widget">
                                <div class="navbar-inner">
                                    <h6><i class="icon-truck"></i>Part Details</h6>
                                </div>
                                <div class="well-smoke">
                                    <form id="part-form" class="form-horizontal" name="part-form" method="POST" action="">
                                    <div class="control-group">
                                        <label class="control-label">Part Number</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->part->getPartNumber(); ?>" readonly="" name="part-part-number"> </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">UPC</label>
                                        <div class="controls"><input class="span12" type="text" value="<?php echo $this->part->getUpcCode(); ?>" readonly="" name="part-upc-code"> </div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h5 class="widget-name"><i class="icon-table"></i>View All Assets</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-picture"></i>Assets</h6>
                                <a class="btn btn-info pull-right" href="/admin/products/parts/view/<?php echo $this->partId; ?>/asset/create"><b class="icon-upload-alt"></b>Add Asset</a>
                                <a class="btn btn-inverse pull-right" href="/admin/products/parts/view/<?php echo $this->partId; ?>"><b class="icon-table"></b>Return to Part</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Label</th>
                                        <th>Asset Type</th>
                                        <th>Video Type</th>
                                        <th>Picture Type</th>
                                        <th>Sequence</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td>
                                            <?php if ($record->getAsset()->getAssetType() == 'partimage') { ?>
                                                <img src="/admin/imagine/<?php echo $record->getAsset()->getHash(); ?>/200/200" alt="<?php echo $record->getAsset()->getLabel(); ?>" />
                                            <?php } ?>
                                        </td>
                                        <td><?php echo $record->getAsset()->getLabel(); ?></td>
                                        <td><?php echo $record->getAssetType(); ?></td>
                                        <td><?php echo $record->getVideoType(); ?></td>
                                        <td><?php echo $record->getPicType(); ?></td>
                                        <td><?php echo $record->getAssetSeq(); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/products/parts/view/<?php echo $this->partId; ?>/asset/edit/<?php echo $record->getPartAssetId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/products/parts/view/<?php echo $this->partId; ?>/asset/view/<?php echo $record->getPartAssetId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/products/parts/view/<?php echo $this->partId; ?>/asset/delete/<?php echo $record->getPartAssetId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
