                    <h5 class="widget-name"><i class="icon-external-link"></i>View Part Asset</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-sitemap"></i>Asset Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/products/parts/view/<?php echo $this->partId; ?>/asset/delete/<?php echo $this->recordId; ?>"><b class="icon-trash"></b>Delete Part Asset</a>
                                        <a class="btn btn-info pull-right" href="/admin/products/parts/view/<?php echo $this->partId; ?>/asset/edit/<?php echo $this->recordId; ?>"><b class="icon-pencil"></b>Edit Part Asset</a>
                                        <a class="btn btn-inverse pull-right" href="/admin/products/parts/view/<?php echo $this->partId; ?>/asset"><b class="icon-table"></b>Return to List</a>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-readonly-partial', array(
    'form' => $this->form,
));
?>
                                    <div class="control-group">
                                        <label class="control-label">Preview</label>
                                        <div class="controls">
                                            <?php if ($partAsset->getAsset()->getAssetType() == 'partimage') { ?>
                                                <img src="/admin/imagine/<?php echo $partAsset->getAsset()->getHash(); ?>/200/200" alt="<?php echo $partAsset->getAsset()->getLabel(); ?>" />
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
